### ISSUE TITLE
Impossible d'ajouter un évent à partir de cette page

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#10]
J'ai voulu créer un évent à partir de la page organisation de ChezNous. J'ai affiché l'agenda et cliqué sur le bouton "ajouté" mais rien ne s'est passé.

![2015-08-19_0922](https://cloud.githubusercontent.com/assets/10626066/9351065/543f0eee-4656-11e5-8d1f-52890745cee8.png)

**Comment by MathieuCoste** [comment]
il semble que l'ajout d'évènement ne fonctionne pas aussi quand on clique sur le + du panel "agenda partagé" (on a le formulaire mais ça tourne en rond au moment de la validation)

**Comment by oceatoon** [comment]
pourtant depuis le POD agenda j'y arrive

**Comment by MathieuCoste** [comment]
pourquoi fermer cette issue ... j'ai le même comportement quand j'essaye d'ajouter une event
