### ISSUE TITLE
tailles images importer

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/communecter#100]
quelles est la taille idéale pour les photos en background des évènements ?
5000 X 3000 trop grand

redimensionner automatiquement les photos ?

**Comment by RaphaelRIVIERE** [comment]
@clement59 , vu que ta bosser dessus je te laisse répondre :)

**Comment by clement59** [comment]
Le serveur est configuré pour n'accepter pour le moment que des fichiers de 2mo ou moins.
Donc la taille idéale est doit être entre 1500x1500.
Sachant que le système les redimensionne à 1000x700 proportionnellement.
