### ISSUE TITLE
depuis la liste membres limité, le mode carte aussi  est limité

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#1002]
https://www.communecter.org/#organization.detail.id.56580ad2dd04521c6f943180

detail orga > mode carto 
on ne voit sur la carte que les 12 users de la userList
par contre si on va sur Communauté > puis mode carto > là c bon 

donc le refactor cachant   une longue liste de user , bug avec la carte sur detail

**Comment by clement59** [comment]
Wep on en parlait avec Sylvain ... Le truc qui serait bien c'est de revoir complètement le fonctionnement de la carto avec l'appel des données. Sinon à chaque fois au premier appel tu charges tout !! ce qui est hyper lourd coté utilisateur. Le problème est le même pour la recherche ...

**Comment by oceatoon** [comment]
+1 pour l'optimisation de performance
mais avant ca c un bug qui empeche la carte de tout afficher

**Comment by clement59** [comment]
Close that with refactorElement
