### ISSUE TITLE
manque bouton "ajouter" timeline et image dans projet

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/communecter#101]
![manque bouton ajouter image](https://cloud.githubusercontent.com/assets/7815986/9744820/285b71e4-567f-11e5-8b10-88476352657d.png)
![manque bouton ajouter timeline](https://cloud.githubusercontent.com/assets/7815986/9744842/411bb9f0-567f-11e5-96b7-e0b966cd00d6.png)

**Comment by oceatoon** [comment]
c'est bouton ne s'affiche pas lorsque le projet est créer depuis le dashboard ORGA
probablement lié a la methode Authorization lié a l'affichage
