### ISSUE TITLE
recherche "nom prénom" <-> "prénom nom"

### ISSUE THREAD

**Issue by Cyrille37** [pixelhumain/communecter#1022]
Salut,

La fonction de recherche (en haut à droite) trouve les gens par "Nom Prénom" mais pas "Prénom Nom". Du coup on a l'impression que la personne n'existe pas sur le réseau.

Cheers

**Comment by clement59** [comment]
ok c'est good mtn, I close

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2016-11-09 14-11-27](https://cloud.githubusercontent.com/assets/8775448/20134874/7f0a72bc-a686-11e6-8c26-8cef27ce5934.png)

![capture d ecran de 2016-11-09 14-11-46](https://cloud.githubusercontent.com/assets/8775448/20134879/86ded582-a686-11e6-85d1-e21d9c45cede.png)

c'est pas bon

**Comment by clement59** [comment]
Vazy dis moi que c'est pas bon ;)

**Comment by RaphaelRIVIERE** [comment]
It's good
