### ISSUE TITLE
code INSEE au lieu de code postal

### ISSUE THREAD

**Issue by Cyrille37** [pixelhumain/communecter#1024]
Salut,
Du côté utilisateur le code postal est évident.
Par contre du côté de l'application le code INSEE serait plus approprié.
Par exemple sur Tours il y a 3 codes postaux et du coup on n'a 3 visions différentes de la ville ...
Cheers.

**Comment by oceatoon** [comment]
en fait , comme peu de personnes connaissent leur code Insee , 
l'application, elle , est basé sur celui ci 
mais pour l'utilisateur on parle de code postal
c'est donc une bonne remarque et c'est deja le cas :)

**Comment by Cyrille37** [comment]
Salut,
Ce que je veux dire c'est que se communecter sur un code postal c'est pas super quand il s'agit d'une ville avec 3 codes postaux.
J'aurais imaginé que le code postal servait à la recherche, et ensuite on se communecte avec le nom de la ville (code INSEE).
Pour ma part je ne vois pas les _citoyens_ en 37000 et 37200 car je suis en 37100. C'est vraiment déroutant et pas pratique du tout.

**Comment by oceatoon** [comment]
ah effectivement en fait c'est un combo insee_codepostal effectivement  
mais tu as raison 
on va y songer lors du refactor multi scope

**Comment by clement59** [comment]
Mais si dans la recherche, tu peux élargir le scope cf photo qui marche comme tu le décrits. 
Cela s'applique aussi à l'agenda communecté et au news à la prochaine mise en prod (dév en local).
Si bon pour toi hésite pas à fermer.
![capture d ecran 2016-07-12 a 16 33 16](https://cloud.githubusercontent.com/assets/6576514/16770821/8e90ce3e-484e-11e6-91d4-c03eb38f7fd1.png)

**Comment by Cyrille37** [comment]
Ok,, merci @clement59 :+1:
