### ISSUE TITLE
Label des boutons trop long

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#1036]
![capture d ecran 2016-07-12 a 15 48 43](https://cloud.githubusercontent.com/assets/6576514/16769260/43f05198-4848-11e6-9f62-c4c2b4c136bb.png)
Je propose:
Editier / modifier position / paramètres / Supprimer

**Comment by RaphaelRIVIERE** [comment]
Corriger sur dev,
Sur Prod sa arrive avec la prochaine mise a jour
