### ISSUE TITLE
bug passage de accueil vers projets/citoyens

### ISSUE THREAD

**Issue by Cyrille37** [pixelhumain/communecter#1037]
Salut,
Je me "communecte" sur "Tours 37100" et il est affiché: 7 citoyens, 2 projets, 2 events, 3 organisations.
![communecter_1](https://cloud.githubusercontent.com/assets/368965/16776550/23d9bf66-4866-11e6-9aa6-a9ffd9f3c0d8.png)

Je clique sur les "projets" et j'arrive sur une page avec "Tous 2", "Citoyens 2".
![communecter_2](https://cloud.githubusercontent.com/assets/368965/16776553/28be5348-4866-11e6-8ed6-ebcfa6608b84.png)

**Comment by oceatoon** [comment]
merci Cyrille , bien vu, on l'a relevé ce WE , tu es synchro  !! bravo

**Comment by RaphaelRIVIERE** [comment]
Corriger
