### ISSUE TITLE
élargir le scope pour "Actualité" [désir]

### ISSUE THREAD

**Issue by Cyrille37** [pixelhumain/communecter#1038]
Salut,
Maintenant que j'ai compris que l'élargissement de scope ne fonctionnait que dans "recherche" et  "agenda" je me dis que ça serait bien aussi pour "Actualités", pour les voir sans changer de code postal.
_Toujours à cause de ma ville à 3 codes postaux ;-)_

**Comment by Kgneo** [comment]
c'est prévu, en cours de développement, et bientôt terminé ! :)

Le 13 juillet 2016 à 05:03, Cyrille Giquello notifications@github.com a
écrit :

**Comment by clement59** [comment]
Déjà terminé :) ... en local, ça arrive en prod ! je close
