### ISSUE TITLE
Orga : Rééditer un membre 

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/communecter#104]
pas possible d'ajouter des tags après ajout d'un membre à un groupe

**Comment by Pierre-Magnin** [comment]
comment peux t on modifier son statut d'administrateur yes/non?

**Comment by RaphaelRIVIERE** [comment]
En cliquant sur le bouton "administrer" on peux gérer le statut des administrateur des membres

![capture du 2016-06-16 16 15 31](https://cloud.githubusercontent.com/assets/8775448/16116379/93d4c1dc-33dd-11e6-8e3b-9860818c2619.png)
