### ISSUE TITLE
Create Event - searchCity

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#1040]
Uncaught TypeError: Cannot read property 'length' of undefined => 
function searchCity() {
        $("#alert-city-found").addClass("hidden");
.......
        **if(searchValue.length == 5) {**
.........
J'ai tapé 59000 en code postal ....

**Comment by RaphaelRIVIERE** [comment]
Je n'ai pas réussi a reproduire l'erreur en local ou dev, @clement59 tu peux retesté pour vérifier si le bug existe toujours ou pas
