### ISSUE TITLE
Fil d'actualités : lien Orga incorrect

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#1055]
![capture du 2016-07-22 16 58 23](https://cloud.githubusercontent.com/assets/8775448/17057872/24428094-502e-11e6-9abd-fc36072e25dd.png)

Dans le fil D'actualité , si quelqu'un a posté une news dans une orga , lorsqu'on l'on clique sur l'orga, on rediriger vers le fil d'actu de l'orga , au lieu de sa fiche d'info

**Comment by clement59** [comment]
C'est fait exprès !! Vote sur DDA communecteur testeur sinon .. ?
