### ISSUE TITLE
Agenda - Bug de l'affichage des étiquettes

### ISSUE THREAD

**Issue by arno974** [pixelhumain/communecter#1066]
Les étiquettes s'affichent en dessous de l'événement de l'agenda. 
Ce comportement est visible lorsque des événements sont affichés une semaine sur l'autre. Dans ce cas l'étiquette de l'événement est caché par l'événement en dessous.

![communecter](https://cloud.githubusercontent.com/assets/425243/17845916/86b145b8-6856-11e6-9d64-024f90bdce6f.png)

**Comment by clement59** [comment]
good
