### ISSUE TITLE
Titre "gestion des tâches" tronqué

### ISSUE THREAD

**Issue by lucbonnin** [pixelhumain/communecter#1083]
PROD : Le titre "gestion des tâches" est tronqué. On ne voit pas l'accent circonflexe et on peut croire à une faute d'orthographe car cela ressemble à des trémas.
Action : modifier le CSS height

Page :
https://www.communecter.org/#project.detail.id.579624d540bb4ea06a26dffb

**Comment by clement59** [comment]
La seule solution que j'ai trouvé est d'enlever l'accent. Ce qui est pas très génant sachant que c'est des majuscule
