### ISSUE TITLE
iframe cartographie intégrable pour site

### ISSUE THREAD

**Issue by FlorentLivin** [pixelhumain/communecter#1112]
Des acteurs ont envie de communiquer et faire connaître la plate-forme Communecter. En discutant avec eux, certains trouveraient ça cool d'intégrer la carto Communecter sur leur site centrée sur leur structure à partir de données GPS par exemple.  Cela permettrait à des acteurs reconnus implantés sur leur territoire (un centre social, une association d'habitants, ...) qui ont un site web visité par beaucoup de citoyens autour d'eux, d'intégrer la cartographie Communecter centrée sur leur structure et faisant apparaître les autres acteurs autour. Lorsque le citoyen clique sur la cartographie pour découvrir les acteurs de son territoire, il est redirigé directement sur Communecter. Ça peut être un moyen de faciliter l'adoption de Communecter par le plus grand nombre au sein d'un territoire.

Il n'y a pas forcément de budget pour ça puisque ce n'est pas indispensable pour eux mais on sent une volonté de donner un coup pouce et de trouver des moyens à leur échelle pour faire connaître Communecter à ceux qui gravitent autour de leur structure.

**Comment by MathieuCoste** [comment]
c'est une super idée :)

**Comment by clement59** [comment]
Excellent flo ! Je le calle en whishlist mais ça pourrait sortir très vite  suivant la ressource dispo en interne :)
Je le vois comme un network (encore plus simple car seulement la carto) en Iframe qui redirige directement avec href="_blank" sur la fiche dans communecter !
Pour la carto, je mettrais uniquement trois/quatre filtres marchant sur une visibilité de rayon géographique : 500m, 1km, 2km, 5km et voila.
Le lien serait dispo sur les fiches de chaque orga qui serait le centre de ce rayon !

**Comment by MathieuCoste** [comment]
trop bien :)

**Comment by clement59** [comment]
Qu'est'ce que tu en penses de nous fermer ça mon tit tango @Kgneo ? ;)

**Comment by Kgneo** [comment]
![capture du 2016-11-09 14-52-03](https://cloud.githubusercontent.com/assets/7578166/20126848/d95ecdde-a68c-11e6-841a-283f21077668.png)
![capture du 2016-11-09 14-52-19](https://cloud.githubusercontent.com/assets/7578166/20126849/e1a18ca2-a68c-11e6-9b82-77dfbbdc9286.png)
![capture du 2016-11-09 14-53-18](https://cloud.githubusercontent.com/assets/7578166/20126853/e8b2943c-a68c-11e6-93e4-7a2a7d3fd745.png)

**Comment by Kgneo** [comment]
Tout à fait ! la feature est prête même s'il faudra rapidement mettre en place un serveur dédié à cette tâche de partage iframe. On pourra déjà s'en servir dès la prochaine livraison en prod :)
