### ISSUE TITLE
Pb de réglages des parametres de confidentialité

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#1129]
Je peux modifier les params de confidentialité alors que je suis adminPending 
![capture d ecran 2016-10-13 a 20 33 58](https://cloud.githubusercontent.com/assets/6576514/19361844/886e1e56-9184-11e6-9898-3d4dee5274c7.png)

**Comment by clement59** [comment]
ATTENTION JE PRECISE JE SUIS SUPERADMIN ET C'est surement du à ça ! à vérifier

**Comment by RaphaelRIVIERE** [comment]
Merci de m'avoir fait perdre 2 min de ma vie ;)

**Comment by clement59** [comment]
That's my boy !!!
