### ISSUE TITLE
Bug réglages confidentialité person

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#1135]
Un nouveau post sur le fil de Communecter "help and debug" de

"bon jour quand je modifie, dans les paramètres de confidentialités, l'adresse mail, de "masqué" à "privé", le changement ne s'enregistre pas" 
Retrouver les news au lien suivant ici

**Comment by RaphaelRIVIERE** [comment]
Corriger a testé

**Comment by clement59** [comment]
good !
