### ISSUE TITLE
Bug on addPerson => searchAutoComplete [erreur 500]

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#1136]
![capture d ecran 2016-10-14 a 16 23 45](https://cloud.githubusercontent.com/assets/6576514/19391000/db210e50-922a-11e6-9929-dc58cd2c3207.png)

**Comment by clement59** [comment]
J'update la vue qui est uniformisé avec les autres mais le searchAutoComplete ne marche pas plus
![capture d ecran 2016-10-14 a 18 13 11](https://cloud.githubusercontent.com/assets/6576514/19394578/0071f980-923a-11e6-9972-a250b5dd4836.png)

**Comment by oceatoon** [comment]
il faut tout refaire dans cette page en faisant ca tu as du voir que ca
existait deja
mais c'est un gros chantier a refaire , donc pour la 0.16 laissons l'ancien
systeme

**Comment by clement59** [comment]
oui mais dans tous les cas, l'ancien bug aussi donc à vouère !
Pas de soucis pour le person il faut juste rajouter la cass lbh dans le json
