### ISSUE TITLE
Bug Element : reseaux sociaux & telegram

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#1140]
![bug](https://cloud.githubusercontent.com/assets/7578166/19413623/33f8ba38-937e-11e6-9017-7180fa9fb23d.png)
on ne peut plus définir ses liens vers les réseaux sociaux,
ni configurer son compte Telegram

**Comment by RaphaelRIVIERE** [comment]
Je prend celui la clem

**Comment by clement59** [comment]
all right man !!

**Comment by RaphaelRIVIERE** [comment]
A testé
