### ISSUE TITLE
notifications : impossible de rafraichir

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#117]
impossilbe de rafraichir les notifications 

FF 410.b9

![2015-09-14_0855](https://cloud.githubusercontent.com/assets/10626066/9844585/a8ec2b70-5ac4-11e5-9810-4fecc0b0b749.png)

**Comment by RaphaelRIVIERE** [comment]
Maintenant c'est possible
![capture du 2016-06-16 16 17 36](https://cloud.githubusercontent.com/assets/8775448/16116410/de65226e-33dd-11e6-9829-c719d8a53f4e.png)
