### ISSUE TITLE
Bug delete follows depuis le Répertoire

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#1219]
J'ai supprimer Happy Culteur de mon répertoire 
1 )  il y est toujours sur le menu Répertoire a droite
![capture d ecran de 2016-11-15 15-08-09](https://cloud.githubusercontent.com/assets/8775448/20303595/8dcd8d66-ab45-11e6-9452-d6dad07e3734.png)

![capture d ecran de 2016-11-15 15-08-18](https://cloud.githubusercontent.com/assets/8775448/20304431/9cd5ca68-ab49-11e6-9d36-b3ecc02e5abf.png)

2) Si je clic sur "citoyens" ou "Tous", il réapparaît 
![capture d ecran de 2016-11-15 15-08-28](https://cloud.githubusercontent.com/assets/8775448/20303704/2488e732-ab46-11e6-9a24-099a5963624d.png)

Obliger d'actualiser pour ne plus l'avoir

**Comment by clement59** [comment]
removefloopdrawerEntity() && mapUrl["directory"][load]=false;
Pour toi bébé @RaphaelRIVIERE

**Comment by clement59** [comment]
on bon je l'ai close direct
mais tu peux tester
