### ISSUE TITLE
Polygone ou marker

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#122]
quand je tape "paris" c bon 
quand je tape Paris,75002 c moins 
et quand je tape : paris 3eme et que je click rue de temple pas bon non plus 
afficher un marker si une addresse et recherché "102 rue de rivoli"

**Comment by Kgneo** [comment]
j'ai modifié pour que les polygones ne s'affichent que sur les villes / villages 
(données de type "city" ou "town").
Pour les autres types de données, un marker est affiché.

**Comment by Kgneo** [comment]
DONE
