### ISSUE TITLE
Vote et ajout de commentaire 

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#1227]
![capture d ecran de 2016-11-16 09-44-36](https://cloud.githubusercontent.com/assets/8775448/20336136/5eb13cf2-abe1-11e6-826a-11093901362f.png)

Je vote et laisse un commentaire 

Mais il n'est afficher nul part 
![capture d ecran de 2016-11-16 09-44-52](https://cloud.githubusercontent.com/assets/8775448/20336158/7b6cf700-abe1-11e6-974b-fca08ba9cb43.png)

**Comment by Kgneo** [comment]
ça marche pour moi.
