### ISSUE TITLE
search avancé 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#124]
![sig search](https://cloud.githubusercontent.com/assets/192076/10095829/bcbea2e2-637d-11e5-855e-f7a46130f2b8.png)

ya des resultat un peu bizarre :)

**Comment by Kgneo** [comment]
bizarre avec la même recherche j'ai des résultats corrects
![capture d ecran 2015-09-28 a 08 50 08](https://cloud.githubusercontent.com/assets/7578166/10125430/80fe8918-65bf-11e5-879e-1a4c670eaeec.png)

**Comment by oceatoon** [comment]
bon bah on va dire que c'est bon alors
a surveiller qd meme

On Mon, Sep 28, 2015 at 2:01 AM, Tristan Goguet notifications@github.com
wrote:

> bizarre avec la même recherche j'ai des résultats corrects
> [image: capture d ecran 2015-09-28 a 08 50 08]
> https://cloud.githubusercontent.com/assets/7578166/10125430/80fe8918-65bf-11e5-879e-1a4c670eaeec.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/124#issuecomment-143597753
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.
