### ISSUE TITLE
Page organisation : Notification d'activités

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#13]
Un message est il envoyé au membre invité dans l'organisation ? Es ce prévu ?

**Comment by oceatoon** [comment]
oui tout el es notification sont prevus
juste deconnecté encore pour le moment

**Comment by MathieuCoste** [comment]
à tester quand ce sera connecté ... un label spécial du type "à venir"  ?

**Comment by RaphaelRIVIERE** [comment]
Je close, les notifications sont mis en place
