### ISSUE TITLE
new design hash navigation

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#135]
must be able to send  a url 
use browser back and fwd

**Comment by oceatoon** [comment]
bon ca semble 
commencer a marcher convenablement 
cependant gros refactor , pour que ca marche 
il ne faut plus appeler showAjaxPanel ou ShowPanel directement 
mais plutot loadByHash

**Comment by clement59** [comment]
Ok c'est good ! Global a voir dans le détail
