### ISSUE TITLE
Module Network: ajouter un bouton "tout cocher - tout décocher"

### ISSUE THREAD

**Issue by Simroubriff** [pixelhumain/communecter#1358]
Lors de l'utilisation du filtrage dans le module network, les cases a cocher des filtres sont par défaut toutes cochées. et ne s'active réellement que lorsque l'on clique dessus une premiere fois.
Cela entraine de la confusion lors de la navigation.
Ex: http://zerowasteprovence.wixsite.com/zerowasteprovence/cartographie
Proposition: ajouter un bouton "tout cocher - tout décocher"

**Comment by RaphaelRIVIERE** [comment]
Je close celui la  car l'issue existe déjà #1357
