### ISSUE TITLE
Photo (Traitement par lot)

### ISSUE THREAD

**Issue by ghost** [pixelhumain/communecter#1384]
Permettre le téléversement de plusieurs photos en même temps (ex.: dans un post, dans un album).
Merci

**Comment by clement59** [comment]
Hello @xSquid pourrais tu me décrire précisément ce que tu penses en détail ... 
Car c'est possible à l'ajout des photos de les téléverser dans un post et de même de selectionner plein de photos et de les déplacer dans un album

**Comment by ghost** [comment]
Salut @clement59,
De mon côté, lors de la création d'un post, il m'est impossible de sélectionner plusieurs photos.
Par contre ça marche pour les albums...comme le bouton s'appelle "Ajouter UNE image", j'ai cru qu'il y avait la même limitation (qui au final semblerait être un bug?).

Tester sur Firefox, Chromium et Vivaldi depuis une Debian.
Mm comportement pour les 3.

**Comment by ghost** [comment]
Issue reportée ici: https://github.com/pixelhumain/co2/issues/898
