### ISSUE TITLE
filtre par type , on perd le focus encours

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#139]
je click sur le filtre le zoom se positionne parfaitement pour voir tout les point
ensuite ce qui m'interresse c'est la REunion 
je zoom sur la reunion , et filtre a nouveau 
ca dézoom alors  a nouveau 
ca peut etre interressant de fixer une zone geo 
je crois que tu faisait un truc similaire dans Demosalithia 
ou alors c t dans le module news jme souviens plus 
wdyt ?

**Comment by Kgneo** [comment]
Avant il y avait une checkbox pour savoir si le panel de droite devait afficher tous les item ou seulement ceux visible sur la carte (en fonction du zoom et de la position)
c'est de ça dont tu veux parler ?
J'ai désactivé cette option parce que ça n'apparaissait pas sur la maquette du nouveau design SIG,
et parce que ça compliquait un peu l'utilisation du SIG, mais je peux le remettre si besoin.
