### ISSUE TITLE
add Orga form bug , version blue (not default/simple)

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#140]
http://127.0.0.1/ph/communecter/person/dashboard
click ajouter une orga
en console on a 
TypeError: Sig.clearMap is not a function
var contextName = "";

**Comment by Kgneo** [comment]
c'est fait pour fonctionner sur le nouveau thème en utilisant la carto du background.
Pour que ça fonctionne sur l'autre thème, il faudrait par exemple charger la carto en background sur la subview. 
Qu'en pensez vous ?

**Comment by oceatoon** [comment]
great idea !!
ca rejoint l'idée qu'on avait eut dans le passer :)

2015-10-05 16:22 GMT+04:00 Tristan Goguet notifications@github.com:

> c'est fait pour fonctionner sur le nouveau thème en utilisant la carto du
> background.
> Pour que ça fonctionne sur l'autre thème, il faudrait par exemple charger
> la carto en background sur la subview.
> Qu'en pensez vous ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/140#issuecomment-145510715
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.
