### ISSUE TITLE
ajouter l'icon collectivité , on search city

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#141]

**Comment by Kgneo** [comment]
DONE

**Comment by oceatoon** [comment]
ya un bug quand on fait une recherche

On Wed, Oct 7, 2015 at 5:53 AM, Tristan Goguet notifications@github.com
wrote:

> DONE
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/141#issuecomment-146054928
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.
