### ISSUE TITLE
Project Form: Localisation

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#143]
Le projectForm ne marche plus sur l'ancienne vue du à l'ajout de l'adresse via la carte
La localisation ne pointe pas au bon endroit lors de la saisie de l'adresse (le marker se retrouve en Afrique)

**Comment by Kgneo** [comment]
je viens de réparer les form sur l'ancien design.
Merci de vérifier si tout fonctionne bien !

**Comment by clement59** [comment]
Le form enregistre de nouveau. Mais quand je replace le marker au bon endroit, il ne se passe rien lorsque j'appuie sur le btn "SAVE".

**Comment by Kgneo** [comment]
je viens de tester, tout a bien fonctionné
