### ISSUE TITLE
optimisation de l'espace carto / panel 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#147]
on pourrait jouer avec l'espace dans le screen 
l'ecarter que quand on a qlq chose a montrer sur la carte sinon le reduire
http://awesomescreenshot.com/0765av7vc6

**Comment by Kgneo** [comment]
J'ai fait une fonction dans mon Sig "centerSimple(center, zoom)" qui se charge de placer le marker en haut du panel. Je pourrais rajouter une ligne pour descendre le panel en même temps.
Sinon, on pourrait aussi jouer sur la transparence du panel, en augmentant le padding-top de #ajaxSV.
Ça permet de garder toujours le panel à la même place, tout en voyant la carte derrière.
J'ai testé sur la page City c'est plutôt pas mal je trouve.
