### ISSUE TITLE
dans les form en changeant la ville le point ne se repositionne pas 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#148]
cp 63340 > 
si on change a Vichel ou autre 
le geocodage ne se depace pas

**Comment by Kgneo** [comment]
je n'arrive pas à récupérer la valeur de la ville selectionnée 
$("#city").val() donne "undefined" 
Quelqu'un sait comment faire !?

**Comment by Kgneo** [comment]
résolu
