### ISSUE TITLE
Problème localisation Event + Barre du haut avec le btn Save qui s'efface lorsqu'on replace le marker

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#152]
![capture d ecran 2015-10-08 a 12 14 24](https://cloud.githubusercontent.com/assets/6576514/10363803/e7d7599a-6db6-11e5-8a29-52a0247de719.png)

J'ai tapé "7 rue Danton 59000 Lille" =>  Il met bien sur une rue Danton mais à côté de Troyes

Et la barre du haut n'est plus dispo quand on revient sur le form après avoir replacé le marker

**Comment by Kgneo** [comment]
**\* J'ai tapé "7 rue Danton 59000 Lille" => Il met bien sur une rue Danton mais à côté de Troyes

> J'ai essayé de rajouter la ville dans la recherche, mais je n'arrive pas à récupérer la valeur de la ville selectionné ($("#city").val() ne fonctionne pas)

**\* Et la barre du haut n'est plus dispo quand on revient sur le form après avoir replacé le marker

> Je n'ai pas réussi à reproduire le bug. 
> Par contre j'avais des problèmes de scoll, ce qui faisait que ce n'était pas facil de parcourir toute la page, selon le remplissage du formulaire (avec / sans geoloc). J'ai réussi à améliorer ça en modifiant un peu le footer de la page, qui produisait des scollbar gênante.

**Comment by Kgneo** [comment]
résolu
