### ISSUE TITLE
organization : add member is down

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#156]

**Comment by clement59** [comment]
Euh on pourra le fermer à la fin de cette journée je pense

2016-02-03 12:55 GMT+01:00 sylvainbarbot notifications@github.com:

> Assigned #156 https://github.com/pixelhumain/communecter/issues/156 to
> @clement59 https://github.com/clement59.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/156#event-537424995.

## 

Clément Damiens
Co-fondateur de l'association Livin'Coop
Diplomé de la formation ITEEM
Département de l'École Centrale de Lille codirigée avec la SKEMA Business
School
_+33-6-98-27-67-24_

_http://youtu.be/dERtXwNjgic http://youtu.be/dERtXwNjgic_
