### ISSUE TITLE
geocodage : assurer au moins sur la ville et le pays

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#162]
assurer au moins le pays 
j'ai taper ca
73 route de bellecobe
97421 , La Riveiere
Reunion

et ca m'a geolocalisé en Allemagne

**Comment by Kgneo** [comment]
je n'arrive pas à reproduire ce bug
parcontre j'ai trouvé un autre bug sur la recherche "complexe" quand on click sur le bouton "...", ça créé des problèmes. D'ailleurs même quand ça marche les résultats ne sont pas terribles.
je me demande si on doit le garde. Je trouve que cette option est trop compliqué, est-ce qu'on garde les 2 modes ? ou est-ce qu'on garde seulement la recherche fulltext ?
