### ISSUE TITLE
instable : apres chgt d'image l'icone (orga) dans le resultat recherche est cassé , ou l'image disparait 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#170]
![image](https://cloud.githubusercontent.com/assets/192076/10513261/6f7b9c44-7357-11e5-9651-aa1ddb1ffadb.png)

![image](https://cloud.githubusercontent.com/assets/192076/10513386/5c8a3a22-7358-11e5-9f3c-129f99a3aba5.png)

**Comment by clement59** [comment]
Ok lé bon je close
