### ISSUE TITLE
create account > on HTML5 locate > prefill country 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#171]
est ce possible de reverse geocoder a partir du lat lon 
renvoyer par le Geoloc HTML5 ?
pour pré remplir le pays sur le formulaire de creation

**Comment by Kgneo** [comment]
Oui oui on peut !
http://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding

2015-10-16 18:40 GMT+11:00 Tibor Katelbach notifications@github.com:

**Comment by Kgneo** [comment]
c'est fait, il faudrait vérifier si ça fonctionne bien chez vous aussi (avec ma position c'est ok)

**Comment by oceatoon** [comment]
top
