### ISSUE TITLE
pouvoir chercher des tags dans la recherche globale

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#178]

**Comment by Kgneo** [comment]
est-ce que c'est toujours à l'ordre du jour ?
est-ce qu'on le fait maintenant ? ou est-ce qu'on le fait après avoir stabilisé le reste ?

**Comment by oceatoon** [comment]
comme tu peux voir il est prevu pour le milestone 0.2

**Comment by Kgneo** [comment]
je l'ai implémenté depuis la page /search, du coup ça marche partout normalement

**Comment by RaphaelRIVIERE** [comment]
ça Fonctionne
