### ISSUE TITLE
Directory - problème url => manque "/communecter/" url 

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#203]

**Comment by oceatoon** [comment]
a quel endroit precisement ?

**Comment by clement59** [comment]
ligne 236 => directory2.php

**Comment by oceatoon** [comment]
ca te le fait tjrs ?

**Comment by clement59** [comment]
Non ça ne me le fais plus mais c'est normal... Je l'avais rajouté en dur dans l'attente que tu le corrige:

$url = ( isset($_GET["isNotSV"]))  ? "openMainPanelFromPanel( '/".$type."/detail/id/".$id."', '".$type." : ".$name."','".$icon."', '".$id."' )" : Yii::app()->createUrl('/communecter/'.$type.'/dashboard/id/'.$id);
