### ISSUE TITLE
Erreur géolocalisatio

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/communecter#213]
Bonjour,*

J'ai accepté le partage des données de géolocalisation et apès avoir sign in la page d'accueil me localise à NOUMEA au lieu de St Leu à la Réunion.

**Comment by Kgneo** [comment]
Fixed

**Comment by oceatoon** [comment]
sur la page public (non connecté ) 
http://127.0.0.1/ph/communecter
j'ai toujours le pb de redirection sur st denis en bourg 
qui n'est pas ou je suis 
faisons comme sur le login (juste un zoom sur la zone)
pour le moment tant a pas une detection parfaite
