### ISSUE TITLE
page organisation : document

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#22]
ici impossible de télécharger un document ici ... il y a un messge "something went wrong" 

https://www.communecter.org/communecter/organization/dashboard/id/55901c1ae41d757a2c59ce90#genericGED

**Comment by oceatoon** [comment]
quelle type de document ?

On Wed, Aug 19, 2015 at 5:34 PM, MathieuCoste notifications@github.com
wrote:

> ici impossible de télécharger un document ici ... il y a un messge
> "something went wrong"
> 
> https://www.communecter.org/communecter/organization/dashboard/id/55901c1ae41d757a2c59ce90#genericGED
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/22.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by MathieuCoste** [comment]
.pdf

**Comment by oceatoon** [comment]
j'ai cleaner effectivement un pdf trop lourd restait affiché 
par contre il y a bien un message pour informer que le fichier n'a pas été telechargé
sinon les pdf et autres type de fichiers fonctionne pas trop mal
