### ISSUE TITLE
Add member in organization

### ISSUE THREAD

**Issue by fluidlog** [pixelhumain/communecter#221]
The member is found (in network...), but not displayed.
When you hit the "enter" key, it display an internal error (500)

File / action  : savemember

Response : 

<h1>CTKException</h1>

<p>Vous ne pouvez pas gérer le type (/home/yannick/projets/ph/modules/citizenToolKit/controllers/link/SaveMemberAction.php:36)</p><pre>#0 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/actions/CAction.php(76): SaveMemberAction->run()
#1 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#2 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(286): CController->runAction(Object(SaveMemberAction))
#3 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(SaveMemberAction), Array)
#4 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('savemember')
#5 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('communecter/lin...')
#6 /home/yannick/projets/ph/pixelhumain/ph/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#7 /home/yannick/projets/ph/pixelhumain/ph/index.php(22): CApplication->run()
#8 {main}</pre>

**Comment by oceatoon** [comment]
when typing in search bar
TypeError: v._id is undefined
