### ISSUE TITLE
Directory2 - bug sur un item sur deux lors de la redirection

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#224]
Bug présent que ce soit pour les projets, organisations, évènements !

![capture d ecran 2015-11-09 a 12 49 14](https://cloud.githubusercontent.com/assets/6576514/11033031/659cf258-86e0-11e5-9ff1-6db170037d38.png)

**Comment by clement59** [comment]
Même problème pour les liens dans les menus de gauche de my organizations, my projects, my events

**Comment by oceatoon** [comment]
"localBusiness" un erreur de typo 
le type etait "LocalBusiness"
merci d'utiliser les type qui sont listé dans le Model 
<?php echo Organization::TYPE_BUSINESS ?>
