### ISSUE TITLE
needs : utiliser la structure generique links

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#233]
j'ai vu que dans needs tu ne faisais pas de liens
c'est pourtant avec cette info qu'on definie le liens entre les entités 
il y a une classe Link.php qui so'occupe de tous ca de facon generique *
https://github.com/pixelhumain/citizenToolKit/blob/master/models/Link.php

**Comment by clement59** [comment]
Link done à l'enregistrement
