### ISSUE TITLE
pourquoi a t on besoin de openMainPanelFromPanel et pas faire ca direct dans showAjaxPanel ?

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#240]

**Comment by Kgneo** [comment]
```
   function openMainPanelFromPanel(url, title, icon, id){
    $(Sig.cssModuleName + " .item_map_list_" + id).click();
    openMainPanel(url, title, icon, id);
}

function openMainPanel(url, title, icon, id){
    showAjaxPanel(url, title, icon);
    showMap(false);

    if(Sig.currentMarkerPopupOpen == null) return;
    var latlng = Sig.currentMarkerPopupOpen.getLatLng();

    Sig.centerSimple(latlng, 14);

    Sig.hidePopupContent(id);
}
```

En passant par openMainPanelFromPanel, on centre la carte sur le marker correspondant, et on ouvre la popup du marker, puis on appel showAjaxPanel.
On peut peut-être faire ça autrement, en passant l'id de l'élément à showAjaxPanel, pour pouvoir centrer la carto depuis showAjaxPanel.

J'avais choisi cette solution pour ne pas modifier le fonctionnement de showAjaxPanel, mais je trouve que ce serait une bonne idée de le faire maintenant.

wdyt ?

**Comment by oceatoon** [comment]
ouaip comme ca showAjaxPanel devient le point d'ouverture unique
on le deplacera ensuite dans api.js
