### ISSUE TITLE
map : mini panel person + city > btn en savoir plus

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#243]
![image](https://cloud.githubusercontent.com/assets/192076/11099935/b15429d0-88c7-11e5-9d82-a30a04c12816.png)

![image](https://cloud.githubusercontent.com/assets/192076/11099991/f3438b92-88c7-11e5-815b-936dfe5b6cbb.png)

**Comment by Kgneo** [comment]
done
