### ISSUE TITLE
orga : panel > btn deplacer marche pas

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#244]
marche pas non plus sur mon detail person

**Comment by Kgneo** [comment]
qu'est-ce que ça fait exactement ? est-ce que la carte s'affiche ?

**Comment by oceatoon** [comment]
TypeError: t is null
....LatLng.DEG_TO_RAD,i=this.MAX_LATITUDE,n=Math.max(Math.min(i,t.lat),-i),s=t.lng*...

en fait j'ai trouvé, le bug vient du manque de lat lon
donc il manque un test 
si ya pas de lat / lon alors on geocode avec les infos qu'on a 
et si on trouve pas on affiche simplement l'icon sur la carte 
lé bon ?

**Comment by Kgneo** [comment]
ah oui c'est pas faux !
