### ISSUE TITLE
bloqué après connexion

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#253]
après connexion et en ayant accepter la géolocalisation je me retrouve bloqué sur une commune qui n'est pas la mienne. Comment faire ?

http://screencast.com/t/J9XKGeIK

**Comment by Kgneo** [comment]
j'ai fais pas mal de modif sur ce process, il faudrait tester à nouveau pour voir si le bug est toujours là ou pas.

**Comment by MathieuCoste** [comment]
je viens de refaire le test sur FF43.0b2 . J'ai accepté de me géolocaliser et je me retrouve directement sur Monistrole sur loire alors que je suis à Vichel (63340) et je ne vois pas comment me communecter . 

question : là je suis sur le serveur de prod et peut être que tes modifs sont faites ailleurs ?

![2015-11-13_1215](https://cloud.githubusercontent.com/assets/10626066/11144976/7a62aa42-8a01-11e5-923c-060704bcf52c.png)

**Comment by oceatoon** [comment]
sans les geo shape ca ne marchera pas
recupere ce module deja
https://github.com/pixelhumain/cityData
tu peux tester chez toi
si tu arrives a lancer le script
*renomme ta collection cities en cities_old juste au cas ou *
https://github.com/pixelhumain/cityData
/cities_with_geoShape/importMongoCities.sh

2015-11-13 15:25 GMT+04:00 MathieuCoste notifications@github.com:

> je viens de refaire le test sur FF43.0b2 . J'ai accepté de me géolocaliser
> et je me retrouve directement sur Monistrole sur loire alors que je suis à
> Vichel (63340) et je ne vois pas comment me communecter .
> 
> question : là je suis sur le serveur de prod et peut être que tes modifs
> sont faites ailleurs ?
> 
> [image: 2015-11-13_1215]
> https://cloud.githubusercontent.com/assets/10626066/11144976/7a62aa42-8a01-11e5-923c-060704bcf52c.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/253#issuecomment-156402377
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by oceatoon** [comment]
pour info @RaphaelRIVIERE 
pour eviter le pb de memoire
j'ai jsute retirer --jsonArray dans le script d'impot mongo
