### ISSUE TITLE
click ma commune > switch map > devrait zoomer sur le point de la commune ou du geo shape 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#261]
chez moi ca reste tres dezoomé
et le panel ouvert 
![image](https://cloud.githubusercontent.com/assets/192076/11182486/a6dc2aaa-8c84-11e5-994b-25207db0ab9e.png)

**Comment by oceatoon** [comment]
un peu comme ca 
![image](https://cloud.githubusercontent.com/assets/192076/11182518/d2aaec0c-8c84-11e5-8753-816a9a161038.png)

**Comment by oceatoon** [comment]
en fait ca le fait dans la plus part des cas
mais je crois que quand je click sur ma commune il prend le zoom sur l'etendu des points 
et pas sur le geoShape de ma Commune 
si ca peut t'aider

**Comment by Kgneo** [comment]
oui effectivement c'est ça.
Mais la question c'est surtout pourquoi dans les données de ta commune tu as autant de point hors de ta commune ???
