### ISSUE TITLE
changement image profil met pas a jour

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#267]

**Comment by Kgneo** [comment]
j'ai réglé le problème pour l'image de profil dans la rightList SIG
Par contre l'image de mon marker ne peut pas se mettre à jour à cause du cache, car le nom de l'image du marker ne change pas.
Serait-il possible, au moment de la génération du marker, de lui donner un nom différent à chaque fois (reprendre le nom de l'image) ?
