### ISSUE TITLE
impossible d'ajouter un membre au projet

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#270]
Nav Chrome

Quand je clique sur le + afin d'ajouter un membre au projet... rien ne se passe

**Comment by MathieuCoste** [comment]
![2015-11-17_0719](https://cloud.githubusercontent.com/assets/10626066/11204155/2e9b988c-8cfc-11e5-9685-4d16e92ff094.png)

**Comment by oceatoon** [comment]
tu confirmes qu'apres F5 ca persiste ?
car chez moi ca marche j'ai bien le panel d'invitation qui s'affiche

**Comment by MathieuCoste** [comment]
oui c'est ok maintenant ... du coup je ne sais pas ce qu'il s'est passé tout à l'heure

**Comment by oceatoon** [comment]
probablemnt une erreur javascript
qui fait peter en cascade
si tu peux t'installer firebug ? tu es sous Firefox ? ou Chrome ?

**Comment by MathieuCoste** [comment]
les deux ;) je passe de l'un à l'autre régulièrement . Ok j'installe Firebug

**Comment by MathieuCoste** [comment]
installé ... je vais essayer de comprendre comment bien m'en servir ... je suis preneur d'une prise en main en accéléré ;)

**Comment by oceatoon** [comment]
t'as pas besoin de l'apprendre vraiment
si tu vois un numero rouge s'afficher sur le scarabé
ce sera une erreur dans la page
tu click dessus et tu auras l'erreur

par contre faire attention , quand tu as un bug que tu n'as pas d'erreur
avant
car le javascript creer des pb en cascade
donc une fois que tu as une erreur , rafraichi
et c'est reparti
si c'est pas clair jte fait un court express en Hangout

**Comment by clement59** [comment]
Salut Mathieu,
Je pense que le problème doit être du à l'apostrophe dans le nom du projet. 
Je vais checker ça !

**Comment by clement59** [comment]
Ok c'est réglé. C'était bien du à l'apostrophe dans le nom projet qui est envoyé en variable dans les fonctions de redirection du nouveau site
