### ISSUE TITLE
ne trouve pas comment valider les changements dans la description d'une organisation

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#271]
Je voulais changer la description de l'organisation "ChezNous" et je ne vois pas comment valider les changements.

Je viens de trouver mais je trouve que pour l'utilisateur lambda ça  n'est pas évident

![2015-11-17_0747](https://cloud.githubusercontent.com/assets/10626066/11204487/b70ca50a-8cff-11e5-8a40-708f9df4dfc9.png)

**Comment by clement59** [comment]
Avec le new design lé bon
