### ISSUE TITLE
dashboard : account info 

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#28]
ce panel prend bcp de place et comme je me connais j'ai pas forcément envie ou besoin de l'avoir sous le nez ;)

quand je clique sur les tags ... je vois qu'il se passe quelque chose mais ne comprends pas vraiment quoi ....

comment est ajouté le TAG rouge en haut à droite ?

difficile d'ajouter sa date de naissance avec le type de calendrier proposé

**Comment by oceatoon** [comment]
tous les pod seront configurable 
on pourra cacher ou montrer les pods de son choix 
et construire son propre dashboard

**Comment by RaphaelRIVIERE** [comment]
Toujours d'actualité ?

**Comment by clement59** [comment]
non
