### ISSUE TITLE
event detail : attendee : design uniform avec projet

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#301]

**Comment by oceatoon** [comment]
que penses tu de coloré ou ajouter un element graphique sur les admin dans la liste des particiapants

**Comment by clement59** [comment]
C'est une idée très intéressante. Et ça rejoint le post #291de sylvain de tout à l'heure !

**Comment by oceatoon** [comment]
le top ce serait d'en faire un widget 
ou deja tout simplement un renderpartial partagé
avec en entrée liste de user

**Comment by clement59** [comment]
done ! à tester !
