### ISSUE TITLE
geocodage : peut etre afficher une liste de proposition

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#329]
qd je ne tape pas d'adrss, pays reunion et cp 97421 
un coup sur 2, le neau point se retrouve en allemagne 

![image](https://cloud.githubusercontent.com/assets/192076/11301090/bb0998e2-8fad-11e5-8afc-353150b9f4dc.png)

je me suis dit qu'il etait peut etre pertinent de faire des propositions 
ou au moins montrer l'addresse envoyer au geocodeur 

il me semblait que c'est ce que tu avais deja fait dans la recherche interne a la carto

**Comment by Kgneo** [comment]
le pay était mal pris en compte 
réunion = "RE". Le RE t'envoyait en allemagne je pense.
J'ai modifié pour "traduire" les code pays en string "RE" = "réunion" etc
ça à l'air de marcher bcp mieux

**Comment by oceatoon** [comment]
c pour plus tard 
je trouve ca plutot bien de faire des propositions ?
comme tu avais fait dans la recherche dans la carto 
wdyt ?
