### ISSUE TITLE
user and orga avatars on add member 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#338]
![image](https://cloud.githubusercontent.com/assets/192076/11337143/13a3d636-9204-11e5-95de-e0d1322c85dc.png)

**Comment by RaphaelRIVIERE** [comment]
![capture du 2016-06-16 17 07 37](https://cloud.githubusercontent.com/assets/8775448/16117787/db4c7e22-33e4-11e6-81f6-09ba9da775ff.png)

C'est fait
