### ISSUE TITLE
applying scope on news entry 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#36]
this will show a news entry on the wall   of the scope
public is visible by every one

**Comment by clement59** [comment]
Yes, good unfinished work...
Pour le moment, on a un label "my wall" => qui scope sur le citoyen qui l'écrit ... Pas très intéressant.
Par contre, les scopes dans le select sont très bien...
Il manque le public !! visible by every one je le trouve bien 
Je pense qu'au niveau des news il faut des settings des deux côtés !!
Le premier est fait : C'est l'auteur avec son niveau de partage
Le deuxième est un setting sur les news que tu souhaites recevoir (pré-établis sur la ville et mon entourage).
À étendre au ActivityStream pourquoi pas !

**Comment by oceatoon** [comment]
yes 
on va devoir aussi integrer la Viralité avec les autres reseaux sociaux

**Comment by Kgneo** [comment]
et la viralité sur Communecter ? (le partage de news)

**Comment by oceatoon** [comment]
c'est de ca que je parle 
voir meme pouvoir choisir les scope de publication 
dans le panel de selection

**Comment by clement59** [comment]
Ya un bon debut ! on close ?

**Comment by oceatoon** [comment]
on passe en 0.2 , il est pas terminer ce feature

**Comment by clement59** [comment]
Je close mais amis ! trop de features dans ce commit et les scopes sont disponibles maintenant
