### ISSUE TITLE
affichage activité = processing interminable

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#366]
Sur le mur d'activité.. je cherche à afficher "activités" et le processing se met en marche et ne s'arrête plus

![2015-11-26_0851](https://cloud.githubusercontent.com/assets/10626066/11417918/1a80b2c6-941b-11e5-84c6-dbb215074c5b.png)

Nav : FF43.0 b6

**Comment by MathieuCoste** [comment]
ça fonctionne sur chrome avec  la même url https://www.communecter.org/communecter/default/simple#news.index.type.citoyen

**Comment by clement59** [comment]
Salut Mathieu,
Pour savoir as-tu supprimé une organisation, un projet ou un évènement?

**Comment by MathieuCoste** [comment]
Salut Clément
non et en plus je ne sais pas comment on supprime une orga, un projet ou un évent
