### ISSUE TITLE
navigation : simplification

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#37]
voir la vidéo . Il s'agit d'une question de la double navigation entre la barre du haut et celle de gauche. Et si on supprimait la barre de nav de gauche.

http://screencast.com/t/fbJZi7w6biiR

**Comment by RaphaelRIVIERE** [comment]
Avec le changement design, je pense que se n'est plus d'actualité , a ré-ouvrir dans le cas contraire ou crée une autre issue
