### ISSUE TITLE
Fil d'actualités

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#373]
Quand on se connecte on arrive sur le fil d'actualités. Qui reste vide ... jene comprends pas comment il fonctionne ? ça n'est pas très engageant d'arriver sur une page vide ... 

J'aimerais vraiment comprendre comment le fil d'actu fonctionne. J'ai mis cette actu https://www.communecter.org/communecter/default/simple#news.index.type.organizations.id.55d43733e41d750f247b23ca?isNotSV=1 ... je pensais la retrouver sur le fil d'actu général...

**Comment by oceatoon** [comment]
je suis plutot d'accord 
ca fait un peu tristouné a la premiere connexion d'arriver sur un espace vide 
pourquoi on irait pas sur ma commune ?
avec des bouton add dans les section? correspondants ?
wdyt ? @Kgneo @sylvainbarbot @clement59

**Comment by MathieuCoste** [comment]
y'a de grande chance que Ma Commune soit vide aussi non ? Et si on arrivait sur la carte en vision large pour voir les endroits où y'a déjà des choses ...
