### ISSUE TITLE
News : ajout

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#38]
lors de l'ajout d'une news via le bouton "ajouter" ... on a page d'ajout et dans le bloc de saisi du texte il y a "describe your organization"... + il serait bien d'avoir un éditeur wysiwyg

![2015-08-21_0639](https://cloud.githubusercontent.com/assets/10626066/9401464/0e7e610e-47d0-11e5-8c11-ccd7c3d4a3ef.png)

**Comment by oceatoon** [comment]
close #38

2015-08-21 8:44 GMT+04:00 MathieuCoste notifications@github.com:

> lors de l'ajout d'une news via le bouton "ajouter" ... on a page d'ajout
> et dans le bloc de saisi du texte il y a "describe your organization"... +
> il serait bien d'avoir un éditeur wysiwyg
> 
> [image: 2015-08-21_0639]
> https://cloud.githubusercontent.com/assets/10626066/9401464/0e7e610e-47d0-11e5-8c11-ccd7c3d4a3ef.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/38.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by oceatoon** [comment]
la prod est mise a jour
