### ISSUE TITLE
my city detail > orga panel avec trop de tags 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#389]
- pas l'image 
- design des tags
- email trop long
  ![image](https://cloud.githubusercontent.com/assets/192076/11436831/d6814d46-9501-11e5-8504-a58372f19f87.png)

**Comment by oceatoon** [comment]
d'ailleurs j'avais pas vu ca pete le panel des acteurs aussi 

![image](https://cloud.githubusercontent.com/assets/192076/11436869/36326ebe-9502-11e5-8400-914eafced03b.png)

**Comment by oceatoon** [comment]
rendre le nom de l'orga clickable

**Comment by Kgneo** [comment]
ok tout est bon
