### ISSUE TITLE
News : la recherche par tag ne semble pas fonctionner

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#397]
Sur le fil d'actualités, le fitre par Scope (btn toolbar) fonctionne bien, mais pas le filtre #Tag.
Quand je click sur un #tag, mon fil d'actu se vide complètement alors que j'ai bien des News avec ce #tag dans mon fil d'actu.
![capture d ecran 2015-11-30 a 09 50 33](https://cloud.githubusercontent.com/assets/7578166/11460789/d8e93812-9747-11e5-8396-8a2993d3ae86.png)

**Comment by Kgneo** [comment]
Si je click sur #Culture :
![capture d ecran 2015-11-30 a 09 52 06](https://cloud.githubusercontent.com/assets/7578166/11460801/0d0ca55c-9748-11e5-9ed4-e0a7179e52f4.png)

**Comment by clement59** [comment]
Close mais à retravailler Milestone 0.2
