### ISSUE TITLE
design panel de recherche

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#407]
![image](https://cloud.githubusercontent.com/assets/192076/11473631/f8abb5e0-978c-11e5-99ae-44096503d370.png)

**Comment by Kgneo** [comment]
le design a été modifié depuis le signalement de ce bug
voilà ce que ça donne maintenant : 
![capture d ecran 2016-01-20 a 11 44 06](https://cloud.githubusercontent.com/assets/7578166/12436640/3528c458-bf6b-11e5-9193-d91d54bb26ac.png)

**Comment by Kgneo** [comment]
mettre la ville et le cp en dessous du nom de l'item

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-21 a 11 20 46](https://cloud.githubusercontent.com/assets/7578166/12467641/0e707e48-c031-11e5-83b1-a84be583f680.png)

**Comment by oceatoon** [comment]
tip top
