### ISSUE TITLE
moteur de recherche : tags + process save new tags for filtering

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#41]
il semble que le moteur de recherche ne trouve pas les tags 

![2015-08-21_0829](https://cloud.githubusercontent.com/assets/10626066/9402607/52dd95e0-47df-11e5-8084-f8253056b479.png)
navigateur utilisé : FF 41.0b2
heure : 8h37 +0200 UTC

**Comment by oceatoon** [comment]
ce n'est pas encore prevu
mais une idée interressante et une facon de remplir les tags qui nous
interresse
ca rejoint le filtre par tags

ca oblige coté data d'avoir un process d'enregistrement au fur et a mesure que les nouveaux tags rentre
pour le moment les tags sont sur l'element en question 
mais pas centralisé, fonctionnalité qui etait prevu pour le moteur de filtre et tagging

**Comment by RaphaelRIVIERE** [comment]
Maintenant le moteur de recherche prend en compte les #tags
