### ISSUE TITLE
Design du formulaire "Add Need"

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#418]
![capture d ecran 2015-12-02 a 09 25 08](https://cloud.githubusercontent.com/assets/7578166/11516296/9a7c6546-98d6-11e5-83aa-41e8b3554eae.png)

**Comment by Kgneo** [comment]
voilà le nouveau design
![capture d ecran 2015-12-15 a 16 58 40](https://cloud.githubusercontent.com/assets/7578166/11827525/d43922dc-a3e0-11e5-9b06-f24510c7ebfe.png)

c'est bon pour vous ?

**Comment by Kgneo** [comment]
idée : éventuellement revoir le texte d'intro (contenu + mettre en valeur) 
(et peut-être aussi faire pareil sur les autres formulaire Add)

idée : mettre un input "name" + textarea "description du besoin" (au lieu d'un seul champ "name" qui fait office de description)

**Comment by clement59** [comment]
Très bonne idée.
En faite la description est à rajouter sur la fiche besoin ... C'était pour
alléger le formulaire de base ! Par contre il est important d'avoir un nom
en plus d'une description.
Ça permet de synthétiser un besoin en trois mots. C'est important pour
celui qui va répondre.

Le 16 décembre 2015 à 01:01, Tristan Goguet notifications@github.com a
écrit :

> idée : éventuellement revoir le texte d'intro (contenu + mettre en valeur)
> (et peut-être aussi faire pareil sur les autres formulaire Add)
> 
> idée : mettre un input "name" + textarea "description du besoin" (au lieu
> d'un seul champ "name" qui fait office de description)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/418#issuecomment-164937239
> .

## 

Clément Damiens
Co-fondateur de l'association Livin'Coop
Diplomé de la formation ITEEM
Département de l'École Centrale de Lille codirigée avec la SKEMA Business
School
_+33-6-98-27-67-24_

_http://youtu.be/dERtXwNjgic http://youtu.be/dERtXwNjgic_

**Comment by oceatoon** [comment]
Tres sympas,  la tristan touch !!
