### ISSUE TITLE
Mes évènements - Menu déroulant

### ISSUE THREAD

**Issue by televb** [pixelhumain/communecter#42]
Dans le menu déroulant en bas à droite, pas de choix possible (encore). Le but de ce menu n'est pas évident comme cela (nothing selected).

**Comment by oceatoon** [comment]
je ne comprends pas quel dropdown ?

**Comment by MathieuCoste** [comment]
ici 
![2015-08-22_0659](https://cloud.githubusercontent.com/assets/10626066/9422664/9311ff6a-489e-11e5-8b1c-39f8d3dff514.png)

**Comment by televb** [comment]
je confirme l'image ci-dessus

**Comment by MathieuCoste** [comment]
et en plus impossible d'aller au bout de la procédure d'ajout d'event
