### ISSUE TITLE
FormRegister : déplacer le champs "address" dans la popup SIG

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#433]
Après avoir trouvé la position par le code postal, si l'adresse (fullStreet) n'a pas été donnée
=> rajoute un champs de texte dans la popup
=> quand on écrit l'adresse dans la popup, on recopie le contenu dans le champs address du formulaire

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-08 a 12 12 40](https://cloud.githubusercontent.com/assets/7578166/11645094/8ee591ca-9da5-11e5-8d23-81663734d9e7.png)

**Comment by clement59** [comment]
C'est vieux ... avec le two step et le nouveau process que tu fais je ferme
