### ISSUE TITLE
texte 'organisation'

### ISSUE THREAD

**Issue by televb** [pixelhumain/communecter#44]
Au niveau d'une page 'Group', pas possible de reprendre tout le texte pour corriger ce qui a été écrit. 
Firefox 40.0.2
Heure : 11:42 (GMT +1)
ScreenCast : http://screencast.com/t/CJHZYePWlD

**Comment by oceatoon** [comment]
il faut que tu click en haut le stylo

2015-08-21 13:50 GMT+04:00 televb notifications@github.com:

> Au niveau d'une page 'Group', pas possible de reprendre tout le texte pour
> corriger ce qui a été écrit.
> Firefox
> Heure : 11:42 (GMT +1)
> ScreenCast : http://screencast.com/t/CJHZYePWlD
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/44.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by televb** [comment]
voila la page, en fait dans le cadre d'écriture, on ne retrouve pas tout le texte.
voir image : 
http://screencast.com/t/wOLwQU9b

**Comment by RaphaelRIVIERE** [comment]
Je viens de testé , ça fonctionne
