### ISSUE TITLE
ouverture 0.2 par un sondage ou questionaire utilisant le module de vote ?

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#443]
ouvrir la 0.1 avec de vrais questions locales ?
basé sur le module de vote ?
ca nous permettrait de demarer avec de vrai demande d'action a des population que l'on connait 
en recoltant des infos 
ca part aussi sur l'esprit democratique ?
wdyt ?

**Comment by clement59** [comment]
Complètement d'accord mais sur la nouvelle version. Il faudrait peut-être
repasser sur le module de vote?

Le 14 décembre 2015 à 18:41, Tibor Katelbach notifications@github.com a
écrit :

> ouvrir la 01 avec de vrais questions locales ?
> basé sur le module de vote ?
> ca nous permettrait de demarer avec de vrai demande d'action a des
> population que l'on connait
> en recoltant des infos
> ca part aussi sur l'esprit democratique ?
> wdyt ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/443.

## 

Clément Damiens
Co-fondateur de l'association Livin'Coop
Diplomé de la formation ITEEM
Département de l'École Centrale de Lille codirigée avec la SKEMA Business
School
_+33-6-98-27-67-24_

_http://youtu.be/dERtXwNjgic http://youtu.be/dERtXwNjgic_

**Comment by oceatoon** [comment]
> Complètement d'accord mais sur la nouvelle version. Il faudrait peut-être
> repasser sur le module de vote?

je l'ai réintégré mais il faudrait clairement faire une premiere passe
dessus
je le met en 0.2 prio 1

**Comment by clement59** [comment]
C'est bon ça !!

Le 14 décembre 2015 à 19:32, Tibor Katelbach notifications@github.com a
écrit :

> > Complètement d'accord mais sur la nouvelle version. Il faudrait peut-être
> > repasser sur le module de vote?
> 
> je l'ai réintégré mais il faudrait clairement faire une premiere passe
> dessus
> je le met en 0.2 prio 1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/443#issuecomment-164519333
> .

## 

Clément Damiens
Co-fondateur de l'association Livin'Coop
Diplomé de la formation ITEEM
Département de l'École Centrale de Lille codirigée avec la SKEMA Business
School
_+33-6-98-27-67-24_

_http://youtu.be/dERtXwNjgic http://youtu.be/dERtXwNjgic_

**Comment by MathieuCoste** [comment]
très bonne idée ... je suis curieux de voir comment affiner en terme d'usages

**Comment by RaphaelRIVIERE** [comment]
Vu que le module de vote est déjà sur prod , on peut close cette issue ?

**Comment by clement59** [comment]
a souhait
