### ISSUE TITLE
Idée : créer une page pour faire exclusivement de la recherche (style page Google)

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#460]
![capture d ecran 2015-12-21 a 15 43 56](https://cloud.githubusercontent.com/assets/7578166/11923576/c87600d8-a7f9-11e5-942e-44dd25dc7117.png)
L'idée c'est de faire une page très simple avec uniquement un champs de recherche au centre de la page, comme sur google + un champ codePostal (ou/et cityName) pour filtrer les résultat par localité.
- Avec un joli design comme sur l'image.
  (par exemple sur l'url communecter.org/search)

On pourrait garder le mot "COMMUNECTER", et replacer la phrase par les champs de texte.

On affiche les résultats sous le champs de recherche, autour de l'arbre. Quand on click sur un résultat, on ouvre la box-ajax comme sur la page login. On peut naviguer sur la partie publique, puis on peut fermer box-ajax pour revenir à la recherche.

Bien sur cette page serait accessible à tout le monde, sans être connecté, ce qui permet d'avoir notre propre page "moteur de recherche" des acteurs locaux :)

Le tout réalisable assez rapidement je pense puisqu'on a déjà une recherche fulltext qui marche !

wdyt ?

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-21 a 19 53 40](https://cloud.githubusercontent.com/assets/7578166/11926911/910473aa-a81c-11e5-8807-18f4adc06558.png)

**Comment by oceatoon** [comment]
c mortel 
recherche
- de lieu 
- dans les tags
- de personne
- d'action simple par mot clef 
- annuaire

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-21 a 20 16 08](https://cloud.githubusercontent.com/assets/7578166/11927303/b992a802-a81f-11e5-806c-192564e405e4.png)

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-21 a 23 15 12](https://cloud.githubusercontent.com/assets/7578166/11930573/b7843238-a838-11e5-83d7-dff71af80596.png)

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-22 a 01 42 07](https://cloud.githubusercontent.com/assets/7578166/11932993/4054f49e-a84d-11e5-8663-c30dad52f6bc.png)

**Comment by oceatoon** [comment]
Oula ca prend une belle forme

**Comment by Kgneo** [comment]
La recherche par tag fonctionne

![capture d ecran 2015-12-22 a 16 08 02](https://cloud.githubusercontent.com/assets/7578166/11948278/46a6d7b2-a8c6-11e5-8473-b3020d153021.png)

**Comment by Kgneo** [comment]
![capture d ecran 2015-12-22 a 18 57 12](https://cloud.githubusercontent.com/assets/7578166/11950580/da321ebc-a8dd-11e5-9411-885e98743b75.png)

**Comment by Kgneo** [comment]
Fonctionnement du filtre par localité cityName / postalCode / departement (champ de texte en dessous du champs principal de recherche)
+
modif design
![capture d ecran 2016-01-26 a 06 13 05](https://cloud.githubusercontent.com/assets/7578166/12561384/00534e3c-c3f4-11e5-9ee6-5251b667e6a5.png)

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-27 a 00 24 17](https://cloud.githubusercontent.com/assets/7578166/12581690/6c174266-c48c-11e5-9448-263a20e39d58.png)

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-27 a 00 30 41](https://cloud.githubusercontent.com/assets/7578166/12581830/3b126e6a-c48d-11e5-9f4c-47f9693419b8.png)
![capture d ecran 2016-01-27 a 00 30 21](https://cloud.githubusercontent.com/assets/7578166/12581831/3b23b288-c48d-11e5-854f-8ad8c94292d3.png)

**Comment by oceatoon** [comment]
cool je crois que je préfère la version sombre contrasté

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-28 a 05 08 56](https://cloud.githubusercontent.com/assets/7578166/12623309/993390b4-c57d-11e5-8917-4bc4fe3e60d9.png)

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-28 a 05 09 29](https://cloud.githubusercontent.com/assets/7578166/12623319/a53fa9ba-c57d-11e5-8ffa-57b3bfc5bb8e.png)

**Comment by oceatoon** [comment]
intéressant 
idée : dans le dernier screen pourquoi pas retourner l'arbre vers le bas
comme s'il était le resultat

inquiétude : n'est on pas entrain de revenir à une interface trop complexe

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-29 a 23 55 47](https://cloud.githubusercontent.com/assets/7578166/12676139/f6f8de04-c6e3-11e5-834b-d319e8846fa9.png)

**Comment by oceatoon** [comment]
sous Mon profil
Mes Association
Mes Projets
Mes ...

ou alors
je me disais onclick ou meme hover du btn annuaire (a gch)
ca pouvait faire apparaitre nos sous elements pour acceder au page
correspondante

**Comment by Kgneo** [comment]
ouep c'est une bonne idée
je pensais aussi remettre le "floopDrawer" sur la droite de la page, pour avoir accès à mes contacts sans passer par la vue directory, comme sur l'autre design
