### ISSUE TITLE
all forms > description shouldn't be mandatory 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#464]
a l'utilisation je me rends compte que les gens ne s'attardent pas sur la description
sur les quick add

**Comment by oceatoon** [comment]
par contre je penses que c'est pertinant d'ajouter le telephone et url , non ?
par obligatoire mais les avoir dans la 1ere fiche de remplissage 
wdyt ?

**Comment by clement59** [comment]
La description était obligatoire juste pour organization. J'ai remove... A tester

**Comment by clement59** [comment]
Pour la question du telephone et de l'url je le switch sur une autre issue
