### ISSUE TITLE
Actualisation nécessaire après rajout d'un contact ou d'une orga

### ISSUE THREAD

**Issue by GDoukhan** [pixelhumain/communecter#478]
Lorsqu'on se connecte à un contact  ou qu'on ajoute une orga, il est nécessaire de rafraichir la page pour que ceux ci apparaissent dans la liste en colonne à côté de Mes contacts. 
Compliqué à comprendre pour end user.
Testé sous FF43 / Windows10

**Comment by clement59** [comment]
Trop global maintenant ! On a fait une bonne passe dessus !
A remettre mais dans le détail
