### ISSUE TITLE
Choix du Pays dans les forms de création

### ISSUE THREAD

**Issue by GDoukhan** [pixelhumain/communecter#479]
Quand on lance la création d'une orga ou autre et qu'on choisit le pays, il y a France et ensuite la liste des outremers. 
Perso je trouve ça étrange

**Comment by oceatoon** [comment]
ce sont des pays dans le sens territoire eloigner
quand tu cherches dans les pays, la Reunion est un pays 
avec un code telephone international 
une TVA differente...
dans nos adresses on met bien La Reunion pas France
