### ISSUE TITLE
Bug dans le Filtre répertoire Où

### ISSUE THREAD

**Issue by GDoukhan** [pixelhumain/communecter#482]
Dans le répertoire, quand on utilise le filtre où le code postal et le code insee fonctionnent.
Mais le nom de la ville (localty) ne remonte aucun résultat.
Testé sur Laragne Montéglin (05300)

**Comment by oceatoon** [comment]
il ya efectivement un probleme avec le zero 
@Kgneo j'ai regardé dans cities le CP est 5300
donc dans les formulaire quand on essaye de connecté a une ville dont le CP serait 05300 on trouve rien 
et si on tape 5300, on a ce message d'eereur Please enter a value between 5 and 5 characters long.
