### ISSUE TITLE
Lier un événément à plusieurs organisations

### ISSUE THREAD

**Issue by GDoukhan** [pixelhumain/communecter#483]
Il me semble indispensable de pouvoir lier un événement à plusieurs organisations, peut être avec des notions de rôles, comme les liens contacts <=> organisations.

**Comment by oceatoon** [comment]
il y a souvent un organisateur d'evenement 
c'est ce qui existe deja
par contre en 0.2 on a prevu de faire des sous evennements
ce qui ressemble beaucoup a ta proposition 
ca permet de modéliser un evennement comme un seminaire ou une exposition
de creer des sous seances et de lier l'organisation ou la personne de cette partie de l'evennement

**Comment by GDoukhan** [comment]
Pas tout à fait d'accord.
Je pense notamment aux collectivités qui peuvent être très tatillones sur ce genre de choses et qui peuvent co-organiser un événement par exemple Commune + Agglo + PNR ou avec le soutien d'une assoc. Sur certaines logiques le sous-événement mais sur d'autres ce sera très compliqué.

**Comment by oceatoon** [comment]
Ah ok c'est pertinent
je le rajoute a la wishlist 
merci
