### ISSUE TITLE
Accéder à l'ensemble du réseau au delà d'une commune

### ISSUE THREAD

**Issue by GDoukhan** [pixelhumain/communecter#484]
Sera t il possible d'accéder au réseau (liste des organisations) comme sur une commune, mais à des niveaux supérieurs : département, région, voir même sur des emprises indépendantes (je pense par exemple aux parcs naturels), voir même à une sélection de l'utilisateur à la souris.

**Comment by oceatoon** [comment]
oui le système permettra de visualiser un annuaire filtré par type d'information sur n'importe quel scope , géographique ou thématique
il faudrait qu'on documente cette fonctionnalité car elle est extrêmement interessante
