### ISSUE TITLE
Problem db syntax with follow option

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#485]
On écrit en DB pour un citoyen qui suit un citoyen "knows"
Serait-il pas plus adapté d'écrire "follows" comme ça on peut l'étendre aux organisations, aux projets, aux évènements, aux votes et tout autres modules?

**Comment by oceatoon** [comment]
pourquoi pas mais j'implémenterais knows pour tous le monde
et refactorerais le nom par la suite
car je pense qu'il doit yavoir qlqs ficelles attachées a ce knows

2016-01-08 11:10 GMT+01:00 clement59 notifications@github.com:

> On écrit en DB pour un citoyen qui suit un citoyen "knows"
> Serait-il pas plus adapté d'écrire "follows" comme ça on peut l'étendre
> aux organisations, aux projets, aux évènements, aux votes et tout autres
> modules?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/485.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by clement59** [comment]
Je passe en wishlist la fonction follows (une personne, un projet, une association) ou utiliser knows en attendant

**Comment by RaphaelRIVIERE** [comment]
@clement59  avec le refactor sur Follows, ce n'est plus d'actualité il me semble, je close
