### ISSUE TITLE
En prod, changer la page d'accueil ?

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#500]
Actuellement quand on va sur www.communecter.org, la page d'accueil est toujours celle-ci : 
![capture d ecran 2016-01-14 a 11 49 46](https://cloud.githubusercontent.com/assets/7578166/12312612/ef6d39c2-bab4-11e5-9939-4641f13b8aea.png)

est-ce qu'on est d'accord pour basculer sur la page de login ?
![capture d ecran 2016-01-14 a 11 53 01](https://cloud.githubusercontent.com/assets/7578166/12312672/63c9edb0-bab5-11e5-8110-3f9e5ea09271.png)

**Comment by oceatoon** [comment]
c juste que la prod n'est pas a jour 
je vais pushé aujourdhui 
ou on attend de regler le bug sur les icones de la carto ?
