### ISSUE TITLE
recherche : Montreuil , il n'y a qu'une reponse alors qu'il y a 4 Montreuil dans cities

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#510]

**Comment by Kgneo** [comment]
j'ai regardé sur la prod, j'ai bien trouvé 4 montreuil

**Comment by Kgneo** [comment]
en local aussi

**Comment by Kgneo** [comment]
![capture d ecran 2016-01-20 a 11 39 48](https://cloud.githubusercontent.com/assets/7578166/12436563/89f5dd64-bf6a-11e5-8ff9-65abc6c01616.png)
