### ISSUE TITLE
Bugs fréquents

### ISSUE THREAD

**Issue by BernardBrunet** [pixelhumain/communecter#518]
J'ai créé un groupe "assemblée des communs Toulouse" et je commence à rentre des projets que rattache au groupe en me disant que cela va dessiner progressivement la carto de l'assemblée toulousaine. Mais il m'arrive plusieurs fois par session de tomber sur le bug "processing" qui ne s'arrête pas. Seul moyen alors me déconnecter puis me reconnecter. De manière général l'accès aux différentes pages est très très lent.

**Comment by oceatoon** [comment]
merci Bernard pour ce feedback
est ce que par hasard tu as prit du temps entre les actions que tu as pu faire 
car si c'est le cas c'est une tache que je dois faire aujourdhui meme
et sinon je suis preneur d'une session pour le voir avec toi sur Hangout si tu as un petit temps a me consacré

**Comment by BernardBrunet** [comment]
Salut Tibor,
Je suis dispos demain jeudi après-midi à partir de 16h pour un hangout.
Ca irait pour toi ?
A bientôt. Bernard.

Bernard BRUNET
06 77 90 14 08

Le 20 janvier 2016 à 12:33, Tibor Katelbach notifications@github.com a
écrit :

**Comment by oceatoon** [comment]
can't repoduce
