### ISSUE TITLE
lier un evennement a un projet 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#52]
on m'a fait une demande assez pertinente 
qui est d'associé un ou plusier events a un projet 
donc de la meme maniere qu'on peut creer un event pour une orga on ferait un event pour un projet 
et du coup avoir un listing events comme pod de la page projet
 wdyt ?

**Comment by oceatoon** [comment]
on se le fait celui ci ?

**Comment by oceatoon** [comment]
j'ai cliké un peu vite sur Close and comment :)

**Comment by oceatoon** [comment]
A faire 
- bouton add event dans la toolbar sur le dash projet
- pod listing des events
- réutiliser le Event Form SV et ajouter les projet dans la liste des Event parent

**Comment by clement59** [comment]
Done
