### ISSUE TITLE
mode deconnecté > ouvrir une orga > clicker fil d'actu , fait rien 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#522]

**Comment by clement59** [comment]
Voici l'erreur : Uncaught ReferenceError: typesLabels is not defined [présent dans views/default/index.php]
var typesLabels = {
  "<?php echo Organization::COLLECTION ?>":"Organization",
  "<?php echo Event::COLLECTION ?>":"Event",
  "<?php echo Project::COLLECTION ?>":"Project",
};

Dans le new design, views/search/index.php ça marche ....
