### ISSUE TITLE
menu onclick ex une orga > utiliser suelement LoadByHash

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#526]
pour que ce soit prit en compte dans la barre d'url 
et que l'historique back fonctionne

**Comment by Kgneo** [comment]
j'ai rajouté loadByHash dans le floopDrawer : sur les item et les bouton "+ ajouter" , 
et dans les bulles info sur la carte.
Je pense qu'il faudra aussi le faire pour les sous-menu
![capture d ecran 2016-01-21 a 12 02 01](https://cloud.githubusercontent.com/assets/7578166/12468341/d1775f38-c036-11e5-9e0f-c79ae8fda64e.png)
