### ISSUE TITLE
Gestion des adresses pour l'import de données

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#529]
Certaines adresses comportent des informations sur l'appartement, le quartier si c'est un numéro bis ou ter etc ...
Mais Nominatim et Google Maps ont du mal à gérer ça, pour la géolocalisation .

Est-que je dois modifier l'adresse depuis le fichier source ? Ou alors je dois procéder autrement ?

**Comment by oceatoon** [comment]
oui je pense que le mieux c'est de modifier l'address 
pense a te mettre un message d'erreur explicite dans error.json
