### ISSUE TITLE
sécuriser le champ de recherche

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#535]
quand on tape des caractères spéciaux comme ( ; " ça provoque des erreurs pas cool du tout

![capture d ecran 2016-01-22 a 12 38 03](https://cloud.githubusercontent.com/assets/7578166/12500221/387b98ba-c105-11e5-97b2-55d64639cbdc.png)
![capture d ecran 2016-01-22 a 12 39 14](https://cloud.githubusercontent.com/assets/7578166/12500212/2f43fb3e-c105-11e5-9b52-99fef50ccbd6.png)

**Comment by oceatoon** [comment]
ah j'ai vu ce bug depuis hier 
mais c'est direct au chargement 
ce n'edst pas que lier a la recherche

**Comment by oceatoon** [comment]
ca semble etre bon
