### ISSUE TITLE
bug news tags accent firefox

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#551]
Error: Syntax error, unrecognized expression: .sigModuleBg #item_panel_map_Étudesenéconomied'énergie

**Comment by clement59** [comment]
Features idea pour les tags ...
Il serait intéressant de mettre en clé le mot tout en minuscule sans spécial caractère et sans espace comme ça on évite les doublons aussi entre ce écrit en majuscule etc

**Comment by oceatoon** [comment]
on va avoir beson d'un bonne outil et d'un bon system
pour uniformiser les tags

**Comment by clement59** [comment]
Je close
