### ISSUE TITLE
my news news sur une autre commune

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#552]
![image](https://cloud.githubusercontent.com/assets/192076/12614916/0eb403e4-c51c-11e5-8038-5a9e1f591722.png)

tu remarqueras que je suis sur MA COMMUNE : Villeneuve-d'Ascq
et que j'ai mes post dans l'actu

**Comment by clement59** [comment]
Bien bien il faut que j'affine tout ça

**Comment by clement59** [comment]
Normalement tu devrais plus avoir tes news sur le fil de villeneuve
