### ISSUE TITLE
moteur de recherche > 59650 > Villeneuve D'ascq > click sur le btn voir les Orgas > boom bug

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#553]
erreur JS
SyntaxError: unterminated string literal
...sNotSV=1&tpl=directory2&type=organizations&insee=59009", "Commune : Villeneuve-

**Comment by oceatoon** [comment]
aussi click MapView > puis revient sur commune vient 
le nouveau panel du haut a disparue

je pense que celui ci concerne un peu plus @clement59 
car j'ai l'impression que les panneaux sont derriere le panel news

**Comment by clement59** [comment]
Yes c'est le bug juste au-dessus created by @RaphaelRIVIERE

**Comment by oceatoon** [comment]
j'ai testé ca m'a l'air bon dans les differentes input de recherche
