### ISSUE TITLE
plugguer openAgenda API 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#561]

**Comment by oceatoon** [comment]
https://openagenda.zendesk.com/hc/fr/articles/201874942-Structure-des-donn%C3%A9es
https://openagenda.zendesk.com/hc/fr/articles/203222571-Get-event-data-through-the-API

**Comment by RaphaelRIVIERE** [comment]
Correspondance : Open Agenda  / Communecter
- title.fr / name
- description.fr ou longDescription.fr / description
- timings.start / startDate (enregistrer en ISODate() )
- timings.start / endDate (enregistrer en ISODate() )
- latitude / geo.latitude
- longitude / geo.longitude
- tags.0.label / tags.0 (non gérer dans Communecter )
- registrationUrl / url (non gérer dans Communecter )
- telephone : telephone (non gérer dans Communecter )

Gérer les adresses :
1) postalCode / address.postalCode
2) Récupérer "address" (1 Route d'Ennezat, 63200 Riom, France) Parser pour récupérer "1 Route d'Ennezat" et l'attribuer à address.streetsAddress
3) Avec la geo et le code postal , on récupere le code insee
4) Avec insee and codePosatl et geo on récupere le nom de la city OU on utilise celle de openagenda city / address.Localyty

Info non traiter par OpenAgenda :
- Type de l'event
- Si c'est public ou non (Mais je suposse qu'il sont tous public sur OpenAgenda, non ?)
- allDay non communiquer

autre info possible non attribuer :
- image
- mots-clés
- conditions de participation: 
- Moyens d'inscription:
- Accessibilité :
- âge du public ciblé

Comment gérer les admins des evenements ? 
Empecher les personnes de modifiers ?

Les données peuvent être accessible en plusieurs langues :
"range": {
        "fr": "21 juin 2015, 09h45",
        "en": "21st June 2015, 09:45"
      },
