### ISSUE TITLE
bug pour un user jsute apres son login email : ￼fildeschamps @ 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#572]
![image](https://cloud.githubusercontent.com/assets/192076/12758586/66d66c0e-c9f6-11e5-8094-c105249953a0.png)

**Comment by clement59** [comment]
Ok c'est remis fixé! j'ai supprimé la news ! 
C'est du à l'ancien vue de l'activity stream ... 
Pour éviter que ça se reproduise, quelqu'un peu commenter en prod dans le model du CTK needs.php ligne 66 la méthode Notification::createdObjectAsParam

**Comment by Kgneo** [comment]
j'ai commenté la ligne et commité
