### ISSUE TITLE
bug scroll dans News sur nouveau design

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#582]
réparer le scroll

**Comment by clement59** [comment]
Ok Tristan, ça fonctionne ! je t'ai fais une petite pass de variable isSearchDesign ! pour pixels, city et citoyens.. Par contre pour orga et projet, il faut injecter la variable dans la barre de menu

**Comment by Kgneo** [comment]
ok, je suis repassé sur orga et projet.
Le scroll marche bien sur "Mon fil d'actu", 
par contre il ne marche pas sur "L'actu communectée" : /ph/communecter/search#search.news

**Comment by clement59** [comment]
Moi ça marche correctement

**Comment by clement59** [comment]
par contre attention mtn ca marche plus sur l'ancien design ....
