### ISSUE TITLE
wording : titre project tasks ou plutot project timeline ?

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#59]
j me demande si project tasks ca fait pas trop orienté taches réélles a réaliser 
cette visualisation est plutot fait pour présenter l'activités et les grandes etapes d'un projet 
wgyt ?

**Comment by clement59** [comment]
Project steps? Project program? Project life?

**Comment by oceatoon** [comment]
project timeline ?

On Mon, Aug 24, 2015 at 4:37 PM, clement59 notifications@github.com wrote:

> Project steps? Project program? Project life?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/59#issuecomment-134177904
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by clement59** [comment]
closed #59
