### ISSUE TITLE
News bug on tags

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#591]
C'est un peu embétant, ca me fait sauter mon fil d'actu sur firefox
Error: Syntax error, unrecognized expression: .sigModuleBg #item_panel_map_Étudesenéconomied'énergie

**Comment by Kgneo** [comment]
à quel endroit et quel moment ça se produit ?

**Comment by clement59** [comment]
Enfaite ce bug était du à un mot clé rentré dans une association. On l'a réglé à la main si je ne me trompe pas. Tib tu confirme?

**Comment by oceatoon** [comment]
oui mais on a pas comprit pourquoi ca faisait bugguer 
le panel tags sur le mode carto 
on l'avait réduit a une asso "jeunesse" qlq chose
à étudier avec Tango pour le régler
