### ISSUE TITLE
setScopeValue("Villeneuve-d plante avec les '

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#593]
a la frappe ca marche pas 
et si on recherche  59650 
ona une erreur
setScopeValue("Villeneuve-d
qui te parlera mieux que moi

**Comment by Kgneo** [comment]
réparé

**Comment by clement59** [comment]
Ok c'est bon... 
Par contre au click du bouton Villeneuve d'ascq dans la vue search/news ca plante !
