### ISSUE TITLE
page cassé mode déloggué

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#594]
se délogguer 
aller ici : http://127.0.0.1/ph/communecter/search#main-col-search

**Comment by Kgneo** [comment]
même chose pour la connexion ?
est-ce qu'on passe définitivement sur le nouveau design ?

**Comment by oceatoon** [comment]
oui je penses c'est definitif

**Comment by clement59** [comment]
Les modal de connexion et de register ne s'affiche plus lorsqu'on vient d'un email (type: invitation, confirmation de compte, etc)

**Comment by oceatoon** [comment]
c'est pas le meme bug
