### ISSUE TITLE
Bug : NomPrenom > mon Répertoire > +Ajouter

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#599]
Cette page ne s'affiche pas dans le design AlphaTango
![capture du 2016-02-05 16 24 16](https://cloud.githubusercontent.com/assets/8775448/12846267/05ffa9e6-cc25-11e5-9ddb-dd19634e4798.png)

Je clique sur mon Nom en haut a gauche, puis sur "Mon répertoire" . Et sur le répertoire je clique sur le bouton "+Ajouter"

**Comment by oceatoon** [comment]
je crois qu'elle jsute pas encore cablé

**Comment by Kgneo** [comment]
bien vu.
J'ai supprimé ce bouton du menu puisqu'on a maintenant le bouton "ajouter" en bas à droite de la fenêtre, qui reste toujours affiché
