### ISSUE TITLE
Barre de menu orga citoyen project event pas très claire

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#601]
On ne voit pas que ceux sont des boutons.
Il faudrait les intégrer à la barre fix du haut ...

**Comment by Kgneo** [comment]
est-ce que ce serait mieux comme ça ?
![capture d ecran 2016-02-08 a 01 49 49](https://cloud.githubusercontent.com/assets/7578166/12872988/4fcda860-ce06-11e5-9c1f-6bb9c9bf38c3.png)

**Comment by clement59** [comment]
Yep c'est mieux comme ça je trouve

**Comment by clement59** [comment]
passé dans l'issue #596
