### ISSUE TITLE
Confidentialité et informations personnelles

### ISSUE THREAD

**Issue by numahell** [pixelhumain/communecter#602]
Les infos comme l'adresse mail, le vrai non si on l'indique, le téléphone, l'adresse postale, les contacts ... bref les données personnelles sont toutes visibles aux autres communecters : pour préserver notre vie privée, ce serait pas mal de pouvoir ne pas les diffuser.

Et sinon, on devrait avoir la possibilité de ne pas saisir d'informations personnelles : l'adresse postale est par exemple obligatoire. Y a t'il un intérêt pour que ça soit obligatoire ?

**Comment by oceatoon** [comment]
> Les infos comme l'adresse mail, le vrai non si on l'indique, le téléphone,
> l'adresse postale, les contacts ... bref les données personnelles sont
> toutes visibles aux autres communecters : pour préserver notre vie privée,
> ce serait pas mal de pouvoir ne pas les diffuser.
> 
> tu as tou à fait raison et on te suis a 100%
> cette limitation est justement dans notre pile d'amélioration
> avant l'ouverture
> 
> Et sinon, on devrait avoir la possibilité de ne pas saisir d'informations
> personnelles : l'adresse postale est par exemple obligatoire. Y a t'il un
> intérêt pour que ça soit obligatoire ?
> 
> l'address est obligatoire , jsute le code insee ou postale
> mais pas la position précise
> ca n'a pas d'interet sauf pour les Organisations ou les évennement

**Comment by oceatoon** [comment]
ce point a bien été traité et sera bientot finalisé 
pour le suivre c'est ici 
https://github.com/pixelhumain/communecter/issues/492
