### ISSUE TITLE
mes contacts : click une personne recharge tjrs mon profile

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#606]

**Comment by Kgneo** [comment]
je viens de tester mais je ne peux pas reproduire ce bug.
Quand tu dis mes contacts, tu parles de "Mon répertoire" ?
Moi quand je click j'ai bien le profil demandé qui s'ouvre

**Comment by clement59** [comment]
J'ai réglé le problème. Il manquait un égal a la condition ligne 20 dans person/DetailAction
