### ISSUE TITLE
reduire peut etre en 1 ligne le titre et retirer communectez vous qd on est loggué

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#613]
![image](https://cloud.githubusercontent.com/assets/192076/12881278/fcc16470-ce61-11e5-8c4c-2f711a392c41.png)

**Comment by Kgneo** [comment]
modifié comme ça :
![capture d ecran 2016-02-12 a 04 01 56](https://cloud.githubusercontent.com/assets/7578166/12983441/6788da58-d13d-11e5-8cbc-7f0c36c5b2a6.png)

**Comment by Kgneo** [comment]
j'ai trouvé une erreur quand on va sur http://localhost:8888/ph/communecter/search#city.detail.insee.98805
(pareil pour tous les codes insee)

![capture d ecran 2016-02-12 a 04 06 54](https://cloud.githubusercontent.com/assets/7578166/12983639/3b02c420-d13e-11e5-9a2c-23c0d7f39d3e.png)

ensuite, on est redirigé vers : 

![capture d ecran 2016-02-12 a 04 08 33](https://cloud.githubusercontent.com/assets/7578166/12983659/4f8575aa-d13e-11e5-942e-a1c800810d55.png)

**Comment by oceatoon** [comment]
+1
