### ISSUE TITLE
Recherche collectivité

### ISSUE THREAD

**Issue by pepone31** [pixelhumain/communecter#614]
un petit bug sur la recherche, qd on cherche 97419, ou Possession on ne tombe plus sur la commune mais sur le mur d'expression

**Comment by oceatoon** [comment]
tu veux dire on trouve bien la commune mais quand on click ca sur news et pas la page commune

**Comment by pepone31** [comment]
oui c'est ça....
je clik il trouve la possession, je fais entrer il dirige vers le mur d'expression

**Comment by Kgneo** [comment]
exact, j'ai trouvé ce bug aussi, c'est réparé.
Quand on click sur le nom d'une ville, on relance une recherche avec le nom de la ville dans le scope.
Si on click sur son CP, on relance une recherche avec le CP

ça permet de gérer le problème des villes qui ont le même nom, mais pas le même CP, et inversement.
