### ISSUE TITLE
Problème dans la recherche par name dans l'annuaire

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#615]
En local dans ma recherche quand je tape le nom d'un projet il me le trouve pas

**Comment by Kgneo** [comment]
c'était un problème de prise en compte des accents.
Du coup j'ai fait les réglages pour que ça ne pose plus de problème pour une recherche "mot-clé" ou "#tag"

**Comment by Kgneo** [comment]
ça serait bien de tester un peu chez vous avant de clôturer la tâche
