### ISSUE TITLE
Champ de recherche caractère spéciaux

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#619]
Deux points:
. Pour les villes avec des tirets du 6 "-", il serait bien que les espaces soient interprétés comme des "-". Pour l'expérience utilisateur c'est tout de même plus top
. L'apostrophe fait sauter la recherche dans l'annuaire, etc

**Comment by Kgneo** [comment]
je suis d'accord, mais si on remplace les espace par des "-", les villes qui ont des noms avec des espaces ne seront plus trouvées...
si on peut le faire en regex c'est cool, mais je suis nul en regex !

Dans globalAutocompleteAction, on a des recherches du genre : 
$queryLocality = array("address.addressLocality" => new MongoRegex("/".$locality."/i"));

Est-ce que quelqu'un sait comment inclure cette règle du "-" dans le regex ?

**Comment by Kgneo** [comment]
pour le bug de l'apostrophe, j'ai fait quelque test, apparemment maintenant ça marche

**Comment by clement59** [comment]
Ok pour moi ... pour les tirets c'est pour les villes (plus présent dans l'annuaire donc peut close)

**Comment by Kgneo** [comment]
quand on recherchait une ville avec un tiret, on n'avait aucun résultat.
J'ai modifié pour garder les tiret, et ça marche impec.
