### ISSUE TITLE
Affichr les notifications - new design

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#620]

**Comment by clement59** [comment]
ok Tib je les ai réaffiché ... dc mtn elles sont en js dans le doc layouts/notifications2.php 
Il reste une bonne passe de design à faire...
Et il reste un truk vraiment bizare... Sur la vue de l'agenda par exemple j'ai deux menu différents ce qui donne cela au scroll (une fois c'est bon l'autre non)
![capture d ecran 2016-02-09 a 15 59 14](https://cloud.githubusercontent.com/assets/6576514/12919944/aadc2628-cf46-11e5-85f4-f84d0dd1fe80.png)
![capture d ecran 2016-02-09 a 15 59 20](https://cloud.githubusercontent.com/assets/6576514/12919943/aad42f22-cf46-11e5-8bfe-09e6b8837e9a.png)

**Comment by clement59** [comment]
Alors un autre point, c'est difficile de s'y retrouver car les méthodes sont assez différentes...
Une plus en php l'autre js. Des docs dupliqués et de l'appel et/ou du render de notification un peu partout (MainSearch/MainSimple, search/index, default/index, communecterController et j'en oublis). De quoi perdre la tête .. Y'a un bon nettoyage à faire en 0.2 sur ce point

**Comment by oceatoon** [comment]
bon je veux bien faire un tour aujourd'hui a 2
si t'es dispo ?
