### ISSUE TITLE
Barre du haut non présente sur toutes les vues notamment le principale

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#627]
![capture d ecran 2016-02-09 a 11 47 10](https://cloud.githubusercontent.com/assets/6576514/12914144/f8de9618-cf22-11e5-9e4b-4c30ac1fd4da.png)
Je mettrais bien la barre dans la vue annuaire, agenda, actualité de search pour garder une cohérence dans le design... En plus sur ces pages je trouve du coup l'appel à l'action pour les notifs et le menu utilisateur un peu isolé.
Wdyt?

**Comment by oceatoon** [comment]
+1
ou alors le passer dans la couche focus menu , ce qui donnerait encore plus de place 
rejoignant un peu cette feature evolutive
https://github.com/pixelhumain/communecter/issues/626
@clement59 tu n'aurais pas fait une faute de frappe SEED FROM DAMS ? c'est ton fournisseur de graine ?

**Comment by clement59** [comment]
BAS tu as vraiment l'esprit mal tourné Mr Katelbach

**Comment by oceatoon** [comment]
@RaphaelRIVIERE vient de proposer aussi de la rendre fixe
et donc de ne pas disparaitre en scrollant 
raison de plus de la mettre dans le focus menu panel
