### ISSUE TITLE
probleme de longueur avec es titre comme dans l'ancien design

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#631]
![capture d ecran 2016-02-09 a 15 47 51](https://cloud.githubusercontent.com/assets/6576514/12919487/8f082b56-cf44-11e5-8934-d434dffcce21.png)

**Comment by Kgneo** [comment]
ok c'est rectifié 
![capture d ecran 2016-02-11 a 12 59 58](https://cloud.githubusercontent.com/assets/7578166/12967930/6b60335c-d0bf-11e5-8300-a986c33ce046.png)
![capture d ecran 2016-02-11 a 13 00 08](https://cloud.githubusercontent.com/assets/7578166/12967931/6b685690-d0bf-11e5-9bc9-61fd8191636a.png)
