### ISSUE TITLE
impossible de "participer" à un événement

### ISSUE THREAD

**Issue by phildu** [pixelhumain/communecter#633]
"something went wrong!! please try again." quand je clique sur participer

**Comment by phildu** [comment]
https://www.communecter.org/#event.detail.id.56ba2ab1dd0452f732fa1549

**Comment by clement59** [comment]
ok ca devrait etre bon

**Comment by phildu** [comment]
bah non toujours pas

**Comment by clement59** [comment]
Oui oui c'est pas encore mise en ligne ... C'est pour que la team de développeurs le test avant !

**Comment by Kgneo** [comment]
ok c'est bon pour moi.
je ferme la tache
