### ISSUE TITLE
menu personnel 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#664]
à propos du menu personnel
 pourquoi pas faire tomber la barre du haut 
 avec les éléments personel
plus grand que la dropdown 
on gagnerait en place

**Comment by oceatoon** [comment]
ca fonctionnerait aussi pour les sous menu orga, event, project

**Comment by RaphaelRIVIERE** [comment]
Tjr d'actualité ? c'était pour l'ancien ou le new design ?
