### ISSUE TITLE
Bug : Affichage Logo

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#666]
Le logo ne s'affiche pas dans différents endroits : 
- Menu du haut 
  ![capture du 2016-02-16 17 36 36](https://cloud.githubusercontent.com/assets/8775448/13077743/29456d3e-d4d4-11e5-9a88-10c7d96aa6ed.png)
- Fil d'actu

![capture du 2016-02-16 17 36 44](https://cloud.githubusercontent.com/assets/8775448/13077749/323d1018-d4d4-11e5-8e8c-cd0a988cf6a9.png)

Voici l'URL appelé pour les images : 
/ph/communecter/document/resized/50x50/upload/communecter/citoyens/56b05d2f94ef47e3047b23cf/tYolYochargement.jpg

**Comment by clement59** [comment]
Tu n'es plus connecté?? ...

**Comment by RaphaelRIVIERE** [comment]
Je l'ai déclarer pour sylvain, il m'a dit , sauf erreur de ma part, que l'url n'est pas le bon , on utilise plus "resized"

**Comment by RaphaelRIVIERE** [comment]
Corrigé
