### ISSUE TITLE
page projet : contributors

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#67]
Je tente d'ajouter ChezNous comme organisation dans le projet mais c'est "démocratie ouverte" qui s'ajoute. 

URL : https://www.communecter.org/communecter/project/dashboard/id/55c84c08e41d75134b8b146d#newContributors

FF 41 0b5
![2015-08-29_1449](https://cloud.githubusercontent.com/assets/10626066/9561957/5b176356-4e5d-11e5-97b0-3f1de8124bf8.png)

**Comment by oceatoon** [comment]
bien trouver 
c'est parce que l'orga et Mathieu coste on le meme mail 
et le test est fait sur l'email 
je regarde ca auj
