### ISSUE TITLE
Follow : Menu Mon Répertoire

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#676]
Lorsque je follow une personne celui si ne s'ajoute pas dans le "menu mon répertoire" , même si on actualise la page.

![capture du 2016-02-18 15 50 42](https://cloud.githubusercontent.com/assets/8775448/13142580/78a52ba6-d657-11e5-9fd4-4188cf613c99.png)

![capture du 2016-02-18 15 51 10](https://cloud.githubusercontent.com/assets/8775448/13142585/7d87c4b2-d657-11e5-8678-0a719d8b33bd.png)

**Comment by clement59** [comment]
Je viens de le pusher à tester !

**Comment by RaphaelRIVIERE** [comment]
ça fonctionne ;) je close
