### ISSUE TITLE
bug titre long toujours présent

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#678]
![capture d ecran 2016-02-09 a 15 47 51](https://cloud.githubusercontent.com/assets/6576514/13151593/1ef91b12-d66b-11e5-9b1c-ffa8fdd2cb07.png)

**Comment by Kgneo** [comment]
j'ai modifié.
ça marche jusqu'à une certaine taille, quand l'écran devient trop petit ça pète, mais il faudra s'en occuper pendant une grosse passe responsive je pense (tout le site est cassé sur les petits écran)
![capture d ecran 2016-02-20 a 00 27 06](https://cloud.githubusercontent.com/assets/7578166/13176774/b3e56232-d768-11e5-8f67-124136601efc.png)

**Comment by Kgneo** [comment]
![capture d ecran 2016-02-20 a 00 29 12](https://cloud.githubusercontent.com/assets/7578166/13176808/fdda50c8-d768-11e5-8eaa-2e19b41189b5.png)
