### ISSUE TITLE
survey : pas simple de revenir sur la plateforme quand on est là 

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#68]
En allant sur survey via la barre de nav de gauche. Et en cliquand sur une entrée j'arrive ici mais ne sait plus comment naviguer à partir de là 

FF 41.0b5

![2015-08-29_1610](https://cloud.githubusercontent.com/assets/10626066/9562282/ad0246f8-4e68-11e5-91f9-fe3d67b611f6.png)

**Comment by oceatoon** [comment]
on a fait ces pages de sondage en mode standalone pour etre envoyé par un
simple lien a qlqun qui ne serait pas inscrit
donc on se concentre sur le sondage plutot que sur le reseau social
mais tu as raison , on va rajouter qlq chose
pour le cas ou on arrive depuis le reseau social

2015-08-29 18:12 GMT+04:00 MathieuCoste notifications@github.com:

> En allant sur survey via la barre de nav de gauche. Et en cliquand sur une
> entrée j'arrive ici mais ne sait plus comment naviguer à partir de là
> 
> FF 41.0b5
> 
> [image: 2015-08-29_1610]
> https://cloud.githubusercontent.com/assets/10626066/9562282/ad0246f8-4e68-11e5-91f9-fe3d67b611f6.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/68.

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by RaphaelRIVIERE** [comment]
Avec les nouveaux design je pense que ce n'est plus d'actualité.
