### ISSUE TITLE
Problème avec les fiches contacts (je pense que c'est réglé en local)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#689]
Et depuis hier j'ai des bugs au chargement des fiches contacts et autres (carrément inaccessibles) avec le message loadByHashMap. Testé avec Chrome et Firefox.

**Comment by oceatoon** [comment]
sur la PROD ?

**Comment by clement59** [comment]
c'est guillaume Doukhan qui l'avait relevé mais je pense qu'on peut le close
