### ISSUE TITLE
Survey : sens de "community selected"? 

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#69]
sur l'écran ci-dessous je ne vois pas à quoi correspnd "community selected" ?

FF 41.0b5

![2015-08-29_1612](https://cloud.githubusercontent.com/assets/10626066/9562292/0644cb00-4e69-11e5-924f-d0831d3a0254.png)

**Comment by oceatoon** [comment]
ce sont les posts les plus liké d'une discussion 
c'est bien ca, @sylvainbarbot  ?

**Comment by RaphaelRIVIERE** [comment]
Je close , il y a eu une refonte du module Discuter, Décider Agir avec le new design
