### ISSUE TITLE
au survole des boutons communectez-moi et le bouton city (rentrer un cp), pas de explanations

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#692]
Ce serait bien de mettre une explication pour ces boutons non?
Ou sinon caché la div d'explication. En effet si on vient de survoler le btn annuaire ou autre, l'explication reste alors qu'on survole "communectez-moi"
wdyt? @sylvainbarbot @oceatoon @Kgneo @RaphaelRIVIERE

**Comment by oceatoon** [comment]
+1 je m'en charge​
