### ISSUE TITLE
En mode déconnecté, problème avec $me

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#693]
undefined variable: me

/Applications/MAMP/htdocs/modules/communecter/views/default/index.php(116)
 <?php $this->renderPartial("menuSmall", array("me"=>$me,"urlPhotoProfil"=>$urlPhotoProfil)); ?>

**Comment by clement59** [comment]
Ok je l'ai réglé.
Par contre en mode déconnecté, il n'y a plus les boutons ... dc plus possible de s'inscrire ni de se connecter

**Comment by clement59** [comment]
![capture d ecran 2016-02-26 a 00 15 23](https://cloud.githubusercontent.com/assets/6576514/13337867/3f36c524-dc1e-11e5-96fb-c57c63805cef.png)

**Comment by oceatoon** [comment]
si tu as ces bugs c'est que tu n'es pas a jour

On Fri, Feb 26, 2016 at 3:16 AM, clement59 notifications@github.com wrote:

> [image: capture d ecran 2016-02-26 a 00 15 23]
> https://cloud.githubusercontent.com/assets/6576514/13337867/3f36c524-dc1e-11e5-96fb-c57c63805cef.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/693#issuecomment-189030606
> .

## 

Tibor Katelbach – Senior Developer
http://oceatoon.org
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.
