### ISSUE TITLE
World Wide Web People and Territories

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#694]
![image](https://cloud.githubusercontent.com/assets/192076/13345995/bb6195ee-dc7c-11e5-9fe5-be61f0f16efb.png)

ca pourrait etre cool de faire 
WORLD WIDE WEB PEOPLE & TERRITORY
donc l'image commence par le classique ecran responsive
on rajouterais un cerveau 
un groupe de personne 
et une notion de territoire
tu vois l'idée ?  
de la personne > au mobile > au web > à la carto > au territoire > au groupe qui sont plein de personne

**Comment by jeremyloreau** [comment]
Très bien. Dites-moi ce que vous en pensez ?
<img width="562" alt="capture d ecran 2016-02-28 a 11 44 25" src="https://cloud.githubusercontent.com/assets/8044105/13378073/ced4912c-de10-11e5-8559-00905479b6b9.png">

**Comment by Kgneo** [comment]
j'aime beaucoup :)

**Comment by RaphaelRIVIERE** [comment]
+1 :)

**Comment by oceatoon** [comment]
j'aime bcp :-)
si on peut juste ne pas centrer sur le continent Americain,
mais plutot Africain
et peut etre mettr eune petite touche de reseau/maillage tout fin  ? wgyt ?
​

**Comment by jeremyloreau** [comment]
Bien vu,
C'est modifié. 
Vous en pensez quoi du maillage ? J'ai peur que ça surcharge un peu trop, nan 
<img width="565" alt="capture d ecran 2016-02-28 a 22 15 00" src="https://cloud.githubusercontent.com/assets/8044105/13380974/f11100ce-de68-11e5-857d-724a338b090d.png">
?
