### ISSUE TITLE
Bug Affichage Mon Répertoire

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#696]
![capture du 2016-02-26 15 39 53](https://cloud.githubusercontent.com/assets/8775448/13351315/429adc10-dc9f-11e5-8f2a-79af81028475.png)

**Comment by clement59** [comment]
C'est du au fiche évènements qui sont plus grande que le reste

**Comment by Kgneo** [comment]
![capture d ecran 2016-02-27 a 08 20 12](https://cloud.githubusercontent.com/assets/7578166/13365742/f585ef8c-dd2a-11e5-854a-c7ea30bb9010.png)
c'est corrigé : les événements font la même taille que les autres
