### ISSUE TITLE
Bug persistant au click d'un bouton

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#698]
Quand on clique le double load est toujours présent !! (Il faut changer de vue pour avoir cet évènement)

Fais péter les news, et effectue une reload peu visible mais tout de même

**Comment by oceatoon** [comment]
ca yé je crois que je lui ai fait sa peau , dites moi ??

**Comment by clement59** [comment]
Ok min fieu tu lui as mis le dernier coup de grâce ! Je close !!
