### ISSUE TITLE
erreur 500 lors d'une tentative d'accés au profil d'un membre

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#7]
à partir d'un projet , j'ai une erreur 500 en cliquand sur la petite flèche à côté du nom "tibor"
![accesprofil](https://cloud.githubusercontent.com/assets/10626066/9160611/0790ca36-3f3c-11e5-9f64-22edf401c027.png)

**Comment by oceatoon** [comment]
On peut ajouter une organisations en tant que contributeur 
qui est une bonne chose mais le lien dans la liste contributors n'est pas bonne 
ni a la creation 
ni au reload de la page
