### ISSUE TITLE
when mouse out of browser viewport , desactivate focus Menu Panel ?

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#702]
je me demandais si ca serait pas moins imposant 
que quand on quitte , l'appli se concentre sur le contenu meme si le menu est ouvert 
et du coup fermerait le focus panel  du menu 
wdyt ?

**Comment by Kgneo** [comment]
j'ai rajouté ça : 
$(document).mouseleave(function(){});
apparement ça marche :)

**Comment by oceatoon** [comment]
+1
