### ISSUE TITLE
Position géographique des orga

### ISSUE THREAD

**Issue by FlorentLivin** [pixelhumain/communecter#734]
Lorsque l'on rentre une adresse précise sur le formulaire pour créer nouvelle organisation, celle-ci n'est pas interprétée et le curseur se met par faut au centre ville

**Comment by oceatoon** [comment]
forent tu peux nous envoyer ton use case STP 
quelle adresse ?

**Comment by FlorentLivin** [comment]
C'est un bug générique pour correction. Cela se passe à chaque fois qu'on rentre une adresse précise.

**Comment by FlorentLivin** [comment]
je ne sais pas si j'ai répondu à ta question

**Comment by oceatoon** [comment]
si c'est systématique alors oui :)

**Comment by FlorentLivin** [comment]
yes

**Comment by Kgneo** [comment]
ça n'arrive pas tout le temps, ça arrive seulement quand l'adresse est inconnue par notre système de géoloc. Quand il ne trouve pas l'adresse précise demandée, il affiche la position de la ville demandée.
Ce n'est pas un bug à proprement parler. C'est juste qu'on atteint les limites du système.
Pour le moment, je peux éventuellement rajouter un message pour préciser que l'adresse n'a pas été trouvée (je crois que ce n'est pas le cas)
Ensuite, on pourrait rajouter une 2eme recherche (quand on ne trouve pas l'adresse) via google.map pour compléter, et avoir plus de chance de trouver des résultats (Raph faisait un truc comme ça il me semble ?)

**Comment by RaphaelRIVIERE** [comment]
Yep je confirme , quand nominatim ne trouve pas je passe par google maps, lundi je te mets la fonction dans sig.js

**Comment by Kgneo** [comment]
top cool :) ça marche bien avec google ?

**Comment by clement59** [comment]
- 1 les mans !

2016-03-06 12:38 GMT+01:00 Tristan Goguet notifications@github.com:

> top cool :) ça marche bien avec google ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/734#issuecomment-192878403
> .

## 

Clément Damiens
Co-fondateur de l'association Livin'Coop
Diplomé de la formation ITEEM
Département de l'École Centrale de Lille codirigée avec la SKEMA Business
School
_+33-6-98-27-67-24_

_http://youtu.be/dERtXwNjgic http://youtu.be/dERtXwNjgic_

**Comment by oceatoon** [comment]
+1
@clement : vide tes message en repondant
sinon ya des bout de message dupliqué comme dans les mails et ta signature

**Comment by FlorentLivin** [comment]
Pour moi les seules adresses interprétées sont celles repositionnées manuellement avec le pointeur. Sinon toutes les adresses entrées textuellement ne se situent pas au bon endroit.

**Comment by Kgneo** [comment]
#734

**Comment by Kgneo** [comment]
#385
