### ISSUE TITLE
News : Public vs Mon Réseau

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#771]
![capture du 2016-03-16 10 49 36](https://cloud.githubusercontent.com/assets/8775448/13804331/7cac1412-eb65-11e5-878c-a3ea29fa8db4.png)

On a rien qui indique si la new que j'ai publié est pour le Public ou pour mon réseau  

![capture du 2016-03-16 10 53 41](https://cloud.githubusercontent.com/assets/8775448/13804355/a1a7612c-eb65-11e5-84a7-da217a583c6f.png)

**Comment by clement59** [comment]
done refactor_news
