### ISSUE TITLE
Ne pas afficher les entités incomplets

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#775]
Tout ceux qui ont  : "state" : "uncomplete"  , ne doit pas apparaittre dans la recherche.

**Comment by Kgneo** [comment]
ok j'ai fait la modif, à tester.
Par contre j'ai commité sur la branche "register_simple" du CTK (erreur de ma part)

**Comment by RaphaelRIVIERE** [comment]
ok super je vais testé

**Comment by Kgneo** [comment]
à fermer si c'est ok.

**Comment by RaphaelRIVIERE** [comment]
ça fonctionne nickel , je ferme
