### ISSUE TITLE
explain how to switch language

### ISSUE THREAD

**Issue by thoka** [pixelhumain/communecter#777]
As it seems, communecter should be available in french and english already. 

Please explain, how language can be switched at https://www.communecter.org

**Comment by oceatoon** [comment]
It is available
but the switch is still manuel , it's in my asap todo list
I'll inform you as soon as it comes out
Thanks for insisting for it :)

**Comment by thoka** [comment]
Perhaps you could guess the language from the requests headers provided by
the browser ?

http://stackoverflow.com/questions/17803702/auto-detect-language-and-redirect-user

2016-03-17 19:11 GMT+01:00 Tibor Katelbach notifications@github.com:

**Comment by oceatoon** [comment]
yes that's part of the plan , but a switcher will also be available

**Comment by oceatoon** [comment]
it is available in the next production update 
should be updated today or tomorow

![image](https://zube.io/files/pixelhumain/2c8cf4b63fe6b57ee1b7c3d0667e3f2f.png)
