### ISSUE TITLE
intégrer la saisie des commentaires dans la même div que la news

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#780]
![capture d ecran 2016-03-21 a 14 39 34](https://cloud.githubusercontent.com/assets/7578166/13910231/e66d2272-ef72-11e5-8067-9d4b18f79854.png)

**Comment by clement59** [comment]
Yep ! on l'a mis en 0.2 cette features ! Je pense que l'issue existe déjà mais je n'arrive à la retrouver.
Bref je passe en 0.2
