### ISSUE TITLE
Import des données Demosalithia

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#783]
Mapping de la table HUMAIN
de Demosalithia vers Communecter : 

PSEUDO : username
MDP : pwd
MAIL : email
COUNTRY : address.addressCountry
VILLE : address.addressLocality
LAT : geo.latitude
LNG : geo.longitude
UNIVERSAL_MSG : shortDescription
- Pour le mot de passe, je vois 2 difficultés : 
- Il y a beaucoup de personnes qui risquent de l'avoir oublié, ou qui ne vont pas le retrouver.
  (personne ne se connecte depuis déjà plusieurs mois)
- Les mdp sont cryptés et il faudrait que passer un script php pour les décrypter

wdyt ?
- Pour les types de compte : 
  Dans les données que je vous ai envoyé, il y a des comptes Citoyens et des comptes Projets (tout était dans la même table)
  C'est l'attribut TYPE_COMPTE qui permet de savoir si on a un Citoyen ou un Projet.

TYPE_COMPTE == 0 : citoyen
TYPE_COMPTE >= 0 : projet

TYPE_COMPTE varie entre 0 et 12

est-ce qu'il est possible de créer des projets quand c'est > 0, et des citoyens si c'est == 0 ?

et tagguer les projets avec les noms suivant ?
TYPE_COMPTE == 1 : Information libre
TYPE_COMPTE == 2 : Partage de matériel
TYPE_COMPTE == 3 : Partage de connaissance
TYPE_COMPTE == 4 : Partage de services
TYPE_COMPTE == 5 : Assemblée populaire
TYPE_COMPTE == 6 : Eco-village
TYPE_COMPTE == 7 : Jardin collectif
TYPE_COMPTE == 8 : Marché Gratuit
TYPE_COMPTE == 9 : Projet Libre
TYPE_COMPTE == 10 : Groupe de travail
TYPE_COMPTE == 11 : Energie Libre
TYPE_COMPTE == 12 : Medecine naturelle

**Comment by RaphaelRIVIERE** [comment]
Pour séparer les citoyens et projets je vais faire un scripts qui va me séparer les deux , parce que le module d'import ne permet d'import que un type de données pour le moment . (ça va etre rapide de faire ça )

Pour les tags je peux les rajouter sans problèmes

**Comment by RaphaelRIVIERE** [comment]
pour le mot de passe? on peux faire en sorte que ça soit considérer comme des personne qu'on invite. du coup elle reçoit un mail qui leur dit qu'elle ont était invite a rejoint communecter que c'est Demosalithia qui les invites et comme ça les personnes invité pourrais enregistrer eu-même leur mdp  
wdyt ?

**Comment by Kgneo** [comment]
perfecto :) 
ok pour les tags et les mots de passe.

**Comment by RaphaelRIVIERE** [comment]
Tu n'a pas le code postal des utilisateurs ? c'est pour retournée la bonne city avec les géoShapes
Sinon je me posé la question ,pour les personnes, si il ne s'agit que des les invités , Est-ce utile d’enregistrer les données telle que la géo la ville et la country , en sachant que lors  de leurs premières connexion il vos passer par l'interface d'enregistrer leur adresse. wydt?

**Comment by RaphaelRIVIERE** [comment]
Au niveau des projects , pour la durée, je mets quoi par défaut ?

**Comment by Kgneo** [comment]
- effectivement, bonne idée, on pourrait se passer des données geo et de l'adresse pendant l'import, comme ça ils sont juste invités et ils reparte de zéro sur communecter. je pense que ça facilitera l'import en + :)
- pour la durée des projets, apparement c'est obligatoire, mais je trouve que ça devrait être facultatif, parce que je pense que pour beaucoup de projet, on ne connait pas la durée exacte, on ne sait pas combien de temps ça va durer.
  Donc il faudrait peut être passer ça en facultatif et ne pas l'indiquer pendant l'import
  @tib qu'en penses-tu ?

**Comment by RaphaelRIVIERE** [comment]
- Pour la durée du projet j'suis d'accord, je crois j'avais commencé a faire pour les données de Simon Sarazin avants qu'on les mettents en orga, du coup faudrait je reprends mon travail mais il y aaura pas mal d'amélioration a faire .
- Du coup autre question qui me vient en tête, la Description je la garde ? Ou alors on laisse l'utilisateur recrée sa description  
- Et l'invitation je le mets au nom de qui ? inviter par Démosalithia ? Je peux aussi ajouter un message personnaliser du genre " Demosalithia vous invite a rejoindre Communecter, Un réseau sociétal libre dans lequel Démosalithia a intégrées" Un truc du genre ^^ si ta un meilleur message j'suis prenneur :)

**Comment by Kgneo** [comment]
- ok pour la durée des projets, ça serait cool de le faire
- oui je pense qu'on va garder la description, ça rempli un peu les profils comme ça, surtout qu'il y a plein de messages super positifs
- oui invité par Demosalithia, et le message je te propose ça : 
  " Demosalithia vous invite a rejoindre Communecter, un réseau sociétal libre conçu comme un bien commun, avec l'aide de Demosalithia. 
  Le site Demosalithia.org sera lui désactivé dans les prochaines semaines, puisqu'il est désormais obsolète, vous trouverez tout en mieux sur Communecter :)

Bonne transition à tous !"

**Comment by RaphaelRIVIERE** [comment]
+1111111111111111 je te fais ça, je pense que lundi j'aurai fini ça :) (pour les personnes)
Pour les projets , le temps de faire les modifs et de voir avec tout le monde pour rendre la date des projets facultatifs

**Comment by Kgneo** [comment]
:+1: :+1: :+1: :+1:

**Comment by RaphaelRIVIERE** [comment]
Bon pour les personnes c'est bon :) 
J'attaque les projets

**Comment by clement59** [comment]
On y presque non? :)

**Comment by RaphaelRIVIERE** [comment]
Oui, Sylvain refait un texte pour mieux expliquer Communecter
