### ISSUE TITLE
bug sur bouton communexion (reste actif)

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#784]
![capture d ecran 2016-03-21 a 18 52 58](https://cloud.githubusercontent.com/assets/6576514/13928503/40819176-ef96-11e5-916d-e7daf73982a3.png)

**Comment by Kgneo** [comment]
normalement, ce cas ne devrait jamais se produire.
Tu as dû  supprimer tes cookies manuellement et recharger la page.

Du coup, on pourrait se demander s'il ne serait pas mieux de laisser ce bouton visible tel quel pour inciter les gens à se re-communecter, dans le cas ou un utilisateur aurait supprimé ses cookies.

Pour l'instant, je le masque quand même.
![capture d ecran 2016-03-23 a 14 22 06](https://cloud.githubusercontent.com/assets/7578166/13974777/f06136e2-f102-11e5-9208-600002a7e014.png)
![capture d ecran 2016-03-23 a 14 22 00](https://cloud.githubusercontent.com/assets/7578166/13974778/f0654340-f102-11e5-95cc-0f2055b354d6.png)

**Comment by clement59** [comment]
ok pour moi
