### ISSUE TITLE
impossible de comprendre comment l'annuaire fonctionne

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#800]
![2016-03-26_0307](https://cloud.githubusercontent.com/assets/10626066/14057441/04ae2e80-f300-11e5-9b5d-6f6724ab2d09.png)

Bizarre je n'arrive pas du tout à faire fonctionner l'annuaire

nav: chrome
26/03, 03:09

**Comment by oceatoon** [comment]
c'est normal ya pas de communecter a Vichel
ou en tout cas pas d'entité créer
on pourra plus tard créer plusieur scope pour chaque bureau de communecteur
mais sinon ya pas mal de chose a Vichel si tu vide la recherche

**Comment by MathieuCoste** [comment]
ok étrange j'avais tenté de jouer avec le cercle pour les approches géographiques ... et là ça fonctionne. C'est cool :)
