### ISSUE TITLE
event: problème sur l'heure début et fin

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#801]
![2016-03-26_0322](https://cloud.githubusercontent.com/assets/10626066/14057503/3fe8d3f4-f302-11e5-94d2-a48dd70aa627.png)

nav: chrome
26/03 , 03:24

**Comment by RaphaelRIVIERE** [comment]
On vient de corriger l'erreur en local, elle sera mis sur le prod à la prochaine mise à jour, qui devrait sortir début semaine prochaine.
