### ISSUE TITLE
actus orga : incohérence d'affichage

### ISSUE THREAD

**Issue by MathieuCoste** [pixelhumain/communecter#807]
![2016-03-26_0356](https://cloud.githubusercontent.com/assets/10626066/14057637/ed04a58c-f306-11e5-8bbe-8b6222171235.png)

**Comment by childee** [comment]
L'incohérence d'affichage se produit lorsque l'on saisi une news dans un mois différent de la dernière news (ici on saisi en mars et la dernière news est de Février).
Que fait-on ? 
Proposition 1 - Lancer un refresh dans le cas ou la news est saisi dans un mois diff du mois courant (bizarre au niveau de la position du form qui est sous le mauvais mois mais gain de place)
Proposition 2- Ajoute le mois courant (ici mars 2016) et le form en dessous, puis le mois de la dernière news et la suite (ca perdrait beaucoup de place au niveau de l'affichage mais plus cohérent).

WDYT ?
