### ISSUE TITLE
Design recherche communectée :

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#836]
afficher les résultats en mode grille
![capture d ecran 2016-04-09 a 21 41 11](https://cloud.githubusercontent.com/assets/7578166/14403247/dcefdae0-fe9b-11e5-8217-6c4c3162b67d.png)

**Comment by clement59** [comment]
c'est beau !!! Déjà dans les répertoires un affichage comme ça serait cool et je pense que dans l'annuaire ce serait cool aussi || Par contre pour agenda je verrais plus une évolution en mode horizontal (type lillelanuit.com ;))

**Comment by RaphaelRIVIERE** [comment]
![capture d ecran de 2016-11-09 14-57-07](https://cloud.githubusercontent.com/assets/8775448/20136150/d2a6bbaa-a68c-11e6-91ea-9c963e36bd9b.png)

c'est bon maintenant c'est le cas.

Est-ce que on duplique ce design sur le répertoire ? dans ce qu'a on laise en amélioration sinon on close
wydt ? @Kgneo @clement59  @sylvainbarbot  @oceatoon

**Comment by clement59** [comment]
Bien sur ! on va passer le répertoire ce design ! c'est déjà dans la wishlist notragora donc ...
