### ISSUE TITLE
bug on https://www.communecter.org/#default.directory > lille > ville entière

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#851]
Du à un gif !! Impossible de scroller du coup...
https://www.communecter.org/communecter/document/resized/50x50/upload/communecter/citoyens/56f3cbba40bb4e5d55f00727/joseerudieravatar.gif 500 (Internal Server Error)

**Comment by oceatoon** [comment]
tu l'as cleaner ?
c'est reglé  ?

On Thu, Apr 14, 2016 at 8:15 PM, clement59 notifications@github.com wrote:

> Du à un gif !! Impossible de scroller du coup...
> 
> https://www.communecter.org/communecter/document/resized/50x50/upload/communecter/citoyens/56f3cbba40bb4e5d55f00727/joseerudieravatar.gif
> 500 (Internal Server Error)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pixelhumain/communecter/issues/851

## 

Tibor Katelbach – Senior Developer - Gérant Bénévole Association Open Atlas
_CAMPAGNE DE CROWDFUNDING EN COURS_

http://www.kisskissbankbank.com/en/projects/communecter-se-connecter-a-sa-commune
projet : https://www.communecter.org/
..·><((((º>·´¯`·.¸¸..><((((º>.¸¸..·.¸¸..><((((º>.¸¸..
La Riviere, La Reunion
e-mail : oceatoon@gmail.com (toujours sur GTalk) oceatoon@gmail.com
skype : oceatoon
Fixe : +262+262343686
Mobile : +262-693918532

Save a tree...please don't print this e-mail unless you really need to.

**Comment by RaphaelRIVIERE** [comment]
@clement59 tjr d'actualité ou on close ?

**Comment by clement59** [comment]
Yes ! Refactor postalCodes
