### ISSUE TITLE
Impossible de créer un événement pour 1 même journée tout le journée 

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#852]

**Comment by Kgneo** [comment]
j'ai créé un event pour le 28 avril (du 28 au 28) en sélectionnant "toute la journée"
mais la donnée enregistre du 28 au 29

**Comment by RaphaelRIVIERE** [comment]
Je remonte se bug, on peut pas mettre à la même la date de fin avec la date début.

**Comment by RaphaelRIVIERE** [comment]
Je viens de testé sur Dev, ça fonctionne
