### ISSUE TITLE
bug sur le fil d'actu des bug

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#879]
j'ai reçu un mail comme ça : 
![capture d ecran 2016-04-28 a 17 19 32](https://cloud.githubusercontent.com/assets/7578166/14877047/a2346ba4-0d65-11e6-96a9-4a70635bdc48.png)

Et en cliquant sur le lien ici, j'arrive sur ça : 
![capture d ecran 2016-04-28 a 17 17 10](https://cloud.githubusercontent.com/assets/7578166/14877058/bf211a6e-0d65-11e6-803c-c10662bbd75d.png)

**Comment by clement59** [comment]
c'est passé dans la nouvelle version de news
