### ISSUE TITLE
Two Step Register > Bug > Localisation automatique

### ISSUE THREAD

**Issue by RaphaelRIVIERE** [pixelhumain/communecter#892]
![capture du 2016-05-03 15 29 06](https://cloud.githubusercontent.com/assets/8775448/14981969/df1d8c80-1143-11e6-8075-f4a4fc7dad06.png)

Lorsqu'on clique sur localisation automatique ont se message d'erreur

![capture du 2016-05-03 15 27 37](https://cloud.githubusercontent.com/assets/8775448/14981982/f932f4fc-1143-11e6-997d-5de94a0c821b.png)

**Comment by aboire** [comment]
problème d'index geo sur cities

Thomas Craipeau

2016-05-03 15:31 GMT+04:00 RaphaelRIVIERE notifications@github.com:

**Comment by RaphaelRIVIERE** [comment]
Ok merci - corriger
