### ISSUE TITLE
add orga > orga exists

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#905]
![image](https://cloud.githubusercontent.com/assets/192076/15280580/e01ff06a-1b42-11e6-89fc-e92f1c353388.png)

**Comment by oceatoon** [comment]
d'ailleur on click , ne fait fait rien
est que ca doit pas nous lier a l'orga ?

**Comment by Kgneo** [comment]
c'est quoi le bug ? design ? @oceatoon

**Comment by oceatoon** [comment]
bah tu vois pas la taille de l'icon ? :)

**Comment by RaphaelRIVIERE** [comment]
![capture du 2016-06-14 15 41 22](https://cloud.githubusercontent.com/assets/8775448/16041458/7b796ac2-3246-11e6-8bdf-b6c4bc894c02.png)

Impossible de scroller, pour voir les autres organismes
