### ISSUE TITLE
404 on commune access

### ISSUE THREAD

**Issue by b3j0f** [pixelhumain/communecter#910]
Lors de l'écran du choix de la commune durant la phase de validation d'inscription, j'ai rafraichi la page par erreur, et à présent, je ne peux pas choisir de commune. Dès que je souhaite voir ma commune, j'ai une belle 404 :)

**Comment by clement59** [comment]
c'est bon ça ?

**Comment by Kgneo** [comment]
j'ai fait une passe sur le two-step la semaine dernière où j'ai réglé pas mal de pb.
je l'ai testé plusieurs fois pour essayer de le faire buguer mais ça marchait bien.
je dirais qu'il faut le re-tester à plusieurs pour vérifier
je viens tout juste de tester, pas de pb. 
A confirmer

**Comment by b3j0f** [comment]
Si tu parles bien de la plateforme en ligne, alors en me connectant, j'ai bien eu accès à l'interface de configuration de l'adresse, que j'ai rempli jusqu'à accéder à l'étape de la photo. Avant de terminer cette dernière étape, j'ai recherché les activités autour de moi, ce qui m'a donné une 404, puis je suis allé dans l'onglet "ma commune", et à nouveau 404

**Comment by RaphaelRIVIERE** [comment]
Je viens de testé en local, ça fonctionne, ça sera corriger avec la prochaine mise à jour sur la plateforme en ligne

**Comment by RaphaelRIVIERE** [comment]
le two-step n'existe plus , je close
