### ISSUE TITLE
Blocage sur "chargement en cours" après le login

### ISSUE THREAD

**Issue by johanricher** [pixelhumain/communecter#911]
Après avoir entré le login/mdp, redirection vers l'url `https://www.communecter.org/#news.index.type.citoyens.id.56c3d3e0dd04522879c1aa88?isSearchDesign=1` avec écran "chargement en cours"

[Ecran de chargement infini.](http://i.imgur.com/Py4ZIne.png)

Ce que j'ai essayé : ctrl-F5 (Firefox), supprimer tous les cookies pour me reloguer "au propre" (Firefox), autre navigateur "vierge" (Chrome, sur lequel je n'avais pas utilisé communecter.org). Sans succès.
Sous Windows 10.
Compte : johan.richer

**Comment by oceatoon** [comment]
salut Johan 
merci pour le bug relevé 
une nouvelle livraison sort cette semaine au plus tard lundi 
devrait régler ce cas de figure 
a bientot 
Tibor

**Comment by clement59** [comment]
tu peux changer d'url en attendant pour naviguer sur le reste du site, par exemple:
https://www.communecter.org/communecter#default.news
Et si tu mets une news dans la ville, ça devrait débloquer ton mur (je pense)
Bien à toi,
Ps: je regarderais dans tous les cas si ton mur plante toujours lundi après la livraison

**Comment by johanricher** [comment]
Super merci pour la solution. Et bravo pour le  taf, le résultat est
puissant, le potentiel est énorme. Tout le monde parle de Communecter ! :)

**Comment by clement59** [comment]
johan a tu supprimé un évènement ou une organisation ?

**Comment by johanricher** [comment]
Non (je n'en ai pas créé encore)

**Comment by clement59** [comment]
[bug relevé] Problem with description in object generate in news type activity (NewsTranslator.php l.42)

**Comment by clement59** [comment]
Je pense que c'est bon Johan. Peux-tu me confirmer et fermer l'issue

**Comment by johanricher** [comment]
Je confirme. :) Réparé depuis une des dernières mises à jour (celle du 27 il me semble). Bravo et merci ! :+1:
