### ISSUE TITLE
Participation non voulue à un événement

### ISSUE THREAD

**Issue by MaiaDereva** [pixelhumain/communecter#912]
Je viens de voir que je suis déclarée comme ayant participé à un événement (passé) alors que ce n'est pas vrai. Comment est-ce possible ? La simple invitation de quelqu'un d'autre m'inscrit comme participante ? Ça craint non ?

**Comment by RaphaelRIVIERE** [comment]
Effectivement, lorsqu'on invite une personne à un événement , cette personne est automatiquement ajouter. Pour la 0.13, on mettra en place une validation de participation a l’événement.

**Comment by clement59** [comment]
+5 ! Il y a un statut invitation à mettre sur les personnes invitées à l'event !

**Comment by clement59** [comment]
Petit refactor event: il faut qu'on s'organise dessus ! Je propose qu'on soit deux pour ce petit refactor !
Invitation / Admin / Combo organizer

**Comment by oceatoon** [comment]
il faut qu'on commence un doc regroupant toutes les améliorations Event
et faire un maximum d'un coup 
on peut reprendre celui de Sylvain , je l'avais complété avec les idées des Nacelles

**Comment by clement59** [comment]
Done les amis à tester ( pas encore en prod )

**Comment by RaphaelRIVIERE** [comment]
J'ai testé sur dev, c'est bon
