### ISSUE TITLE
notification hover disparait

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#923]
Problème d'accès fenêtre des notifications :
Quand je clique sur la petite cloche des notifications (en haut à droite) et que j'essaye de cliquer sur la fenêtre pop-up, celle-ci s'en va si ma souris passe sous la cloche ou sous ma photo de profil.
Pour que je puisse cliquer sur la fenêtre, je dois passer par la barre de recherche à gauche de la cloche, et de là aller sur la fenêtre pop-up.

**Comment by Kgneo** [comment]
je n'arrive pas à le reproduire. Testé sur firefox et chrome.
ça persiste chez toi ? @oceatoon

**Comment by oceatoon** [comment]
sur prod et local ,  je descend pas trop vite du bouton notification
