### ISSUE TITLE
vote up down etc comment à unifier avec ceux de news

### ISSUE THREAD

**Issue by clement59** [pixelhumain/communecter#925]

**Comment by clement59** [comment]
à tester les amis !

**Comment by RaphaelRIVIERE** [comment]
![capture du 2016-06-14 10 45 42](https://cloud.githubusercontent.com/assets/8775448/16033475/33223afc-321d-11e6-9ff8-2e8847d45766.png)

J'ai pu voté plusieurs fois à la fois pour le up et down

**Comment by RaphaelRIVIERE** [comment]
testé sur dev
