### ISSUE TITLE
Erreur js leaflet sur les fil d'actu

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#930]
leaflet.js:8 Uncaught TypeError: Cannot read property '1' of null

Tester avec Lille par exemple

**Comment by clement59** [comment]
Enfaite un utilisateur qui n'a pas validé son twostep register  (id :5746f19b40bb4ecb27ac1390) avec le label "two_steps_register":"true",
Elle a donc pu enregistré une organisation. Et la lecture de sa geo inexistante dans les news engendre l'erreur leaflet.js

**Comment by clement59** [comment]
Tu as testé avec de la mauvaise data ? J'ai maté le code ! Ça devrait être bon à fermer !
