### ISSUE TITLE
orga : add member , bloquer le click ajouter sinon on peut clicker plusieur fois

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#932]

**Comment by oceatoon** [comment]
translate bouton search

**Comment by oceatoon** [comment]
bug : si invite n'existe pas : You have to fill the city of the organisation

**Comment by oceatoon** [comment]
sur la fiche invite ya pas les btns menu detail, actu, communauté ...etc

**Comment by clement59** [comment]
J'ai pushé sur dév ! peux tu tester ?

**Comment by oceatoon** [comment]
presque bon 
il reste tjrs : au click le btn n'est pas désactivé, donc les acharnés qui click plein de fois ... 
fait un coup de mitraillette sur le btn add, tu vas le voir

**Comment by RaphaelRIVIERE** [comment]
J'ai testé ça fonctionne, je close
