### ISSUE TITLE
BUGS INTERFACE

### ISSUE THREAD

**Issue by xavcan** [pixelhumain/communecter#94]
un petit problème avec la fiche d'inscription on a une petite vignette qui traine juste en bas près du submit et du coup si pas gaffe on perd le form. mais ça marche. Ok pour septembre. 
bouton Add asso c'est fini, planté... je suis trop fort

**Comment by xavcan** [comment]
2 minutes et c'est reparti. vous êtes trop forts. Mais pour créer communauté. hein pena

**Comment by RaphaelRIVIERE** [comment]
Je close, je pense que ce n'est plus d'actualité
