### ISSUE TITLE
Project TAsks : Ajouter where 

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communecter#96]
que penses tu d'ajouter un "where" sur les taches de la timeline ?
permettrait mem de faire un visualisation cartographier des taches

wdyt ?

**Comment by oceatoon** [comment]
j'ai pensé a ca , en remplissant des atelier et des conference sur la timeline projet communecter

**Comment by clement59** [comment]
Ajout des évènements à leur timeline avec le lieu
