### ISSUE TITLE
sécurisation two-step

### ISSUE THREAD

**Issue by Kgneo** [pixelhumain/communecter#960]
=> masquer les nouveaux boutons de droite pour empêcher le user de sortir du process
=> désactiver le bouton "CO" dans le menuTop
=> rajouter un bouton "déconnecter", pour pouvoir sortir du process et retourner sur la page d''accueil en mode déco

**Comment by RaphaelRIVIERE** [comment]
Je viens de testé sur Dev, c'est bon pour les 3 points, je close
