### ISSUE TITLE
Problème d'affichage sur écran peu large

### ISSUE THREAD

**Issue by Elm7** [pixelhumain/communecter#976]
Bonjour !
Dans le fil d'actualité, l'affichage n'est pas adapté pour les écrans peu large (1024pix) : les petites boîtes ne sont pas en face à gauche et à droite mais en dessous à gauche et à droite. Et les ronds avec tirets ne se sont pas placés sur l'axe au milieu mais sont vers l'extérieur dans le vide… Le reste se passe bien avec les icônes latérales qui se placent plus ou moins sur le contenu.

**Comment by Kgneo** [comment]
![capture d ecran 2016-06-20 a 16 21 04](https://cloud.githubusercontent.com/assets/7578166/16183933/93653f8c-3703-11e6-942d-fc8e55d95b44.png)

**Comment by Elm7** [comment]
Merci pour la copie d'écran. Au début je me demandais ce que c'était que ces ronds avec les tirets. Bon, c'est un détail en fait. Ce n'est pas prioritaire ;)

**Comment by clement59** [comment]
Je close !
