### ISSUE TITLE
user case 1 VPV (votez pour vous)

### ISSUE THREAD

**Issue by Pierre-Magnin** [pixelhumain/communecter#99]
User case one 
selection d'un pays Réunion ok (je chercher LA Réunion mais j'ai trouvé)
on ne peut mettre qu'un code postal de commune (5 chiffres) et pas de région (2 à 3 chiffres)
or le projet a une portée régionale et pas de siège social localisé

**Comment by Pierre-Magnin** [comment]
user joy:
sympa la petite phrase de Hegel à la place du sablier quand le serveur mouline

EDIT : c'est un peu long la moulinettre après avoir rempli le formulaire de création d'un projet et cliquer sur "Save", je vais la connaitre par coeur la phrase de Hegel ;-)

EDIT 2 : si on veut chicaner sur la forme , il manque la Majuscule à la phrase de Hegel "La liberté ...."

**Comment by Pierre-Magnin** [comment]
quand je clique sur "add an organization"
un formulaire s'affiche quelques secondes puis disparait 
en ne laissant que "référencer votre oragnisation"

c'est pas instinctif du coup faire une recherche qui aboutit sur "0 résult cliquez ici"

**Comment by Pierre-Magnin** [comment]
le bouton save n'est pas au même endroit dans créer un projet et créer une organisation

**Comment by RaphaelRIVIERE** [comment]
Avec le changement du design et des amélioration apporter , je pense que ce 'est plus d'actualité. Ré-ouvrir une issue en cas de problème ou d'amélioration
